kbase/workspace_deluxe

RELEASE_NOTES.txt

per issue https://github.com/kbase/workspace_deluxe/issues/8

updated release notes

---

src/us/kbase/typedobj/core/ExtractedMetadata.java
src/us/kbase/typedobj/core/MetadataExtractor.java
src/us/kbase/typedobj/core/MetadataNode.java
src/us/kbase/typedobj/core/TypedObjectValidationReport.java
src/us/kbase/typedobj/test/MetadataExtractionTest.java
src/us/kbase/typedobj/test/files/MetadataExtraction/KB.spec

for testing purposes.
Also minor docs updates.

Restore @searchable annotation and tabs to metadata tests

---

build.xml
lib/biokbase/workspace/baseclient.py
lib/biokbase/workspace/client.py
lib/javascript/workspace/Client.js
src/us/kbase/workspace/WorkspaceClient.java
src/us/kbase/workspace/WorkspaceServer.java
src/us/kbase/workspace/kbase/ArgUtils.java
src/us/kbase/workspace/kbase/HandleIdHandlerFactory.java
src/us/kbase/workspace/kbase/InitWorkspaceServer.java
src/us/kbase/workspace/kbase/TokenProvider.java
src/us/kbase/workspace/kbase/WorkspaceServerMethods.java
src/us/kbase/workspace/test/database/mongo/ShockBlobStoreTest.java
src/us/kbase/workspace/test/kbase/HandleTest.java
src/us/kbase/workspace/test/kbase/JSONRPCLayerTest.java
src/us/kbase/workspace/test/kbase/JSONRPCLayerTester.java
src/us/kbase/workspace/test/kbase/LoggingTest.java
src/us/kbase/workspace/test/scripts/ScriptTestRunner.java
src/us/kbase/workspace/test/workspace/WorkspaceTester.java
test/performance/ConfigurationsAndThreads.java
test/performance/GetObjectsLibSpeedTest.java

Also updates to recompiled handle jars
Waiting on https://github.com/kbase/jars/pull/49

Update to latest common jar & recompile

---

.classpath
build.xml
src/us/kbase/workspace/kbase/HandleIdHandlerFactory.java
src/us/kbase/workspace/kbase/InitWorkspaceServer.java
src/us/kbase/workspace/test/kbase/HandleTest.java
src/us/kbase/workspace/test/kbase/JSONRPCLayerTest.java
src/us/kbase/workspace/test/kbase/JSONRPCLayerTester.java

Also make a portion of the tests pass against the new auth service
Also also fixed the client build

Clarify message when save fails due to inaccessable handle

---

src/us/kbase/workspace/database/Workspace.java
src/us/kbase/workspace/test/workspace/WorkspaceTest.java

Also fix workspace test. Not clear how this got past multiple commits.

Drop ref search max size to 10K based on new timings

---

src/us/kbase/workspace/database/Workspace.java
src/us/kbase/workspace/database/WorkspaceDatabase.java
src/us/kbase/workspace/database/mongo/MongoWorkspaceDB.java
src/us/kbase/workspace/test/workspace/WorkspaceTest.java

preparation for returning paths

 Refactor search code to simplify IO

---

.classpath
build.xml
docsource/buildandconfigure.rst
src/us/kbase/workspace/database/Workspace.java
src/us/kbase/workspace/test/controllers/handle/HandleServiceController.java
src/us/kbase/workspace/test/database/mongo/ShockBlobStoreTest.java
src/us/kbase/workspace/test/kbase/HandleTest.java
src/us/kbase/workspace/test/kbase/JSONRPCLayerTest.java
src/us/kbase/workspace/test/scripts/ScriptTestRunner.java
src/us/kbase/workspace/test/workspace/WorkspaceTester.java

Needed shock & handle controller updates.

TASK-804 Make tests pass with auth2

---

src/us/kbase/workspace/database/Workspace.java
src/us/kbase/workspace/database/WorkspaceDatabase.java
src/us/kbase/workspace/database/mongo/MongoWorkspaceDB.java
src/us/kbase/workspace/database/mongo/QueryMethods.java
src/us/kbase/workspace/test/kbase/JSONRPCLayerTest.java
src/us/kbase/workspace/test/kbase/JSONRPCLayerTester.java
src/us/kbase/workspace/test/workspace/WorkspaceTest.java

Refactors the workspace resolution methods to simplify and remove where possible.
Also fixes a workspace bug where an admin could delete a locked workspace.
Also also adds some missing tests for un/deleting workspaces.

TASK-806 Prep for adding admin version of get_workspace_info

---

.classpath
build.xml
deploy.cfg.example

Now compiles with java 8.
Update auth jar.
Move deploy.cfg -> deploy.cfg.example.

Small updates: java 8, auth jar, deploy.cfg

---

src/us/kbase/workspace/database/ObjectInformation.java
src/us/kbase/workspace/database/ObjectResolver.java
src/us/kbase/workspace/database/PermissionsCheckerFactory.java
src/us/kbase/workspace/database/Workspace.java
src/us/kbase/workspace/test/workspace/PermissionsCheckerFactoryTest.java

The current object resolution code is very complex and hard to work on. Isolated the code to a new ObjectResolver class with a reasonably sane interface to make it easier to refactor the code for simplicity and to add the new features that are needed.
TODO:
* actually refactor the code so it's not so complex
* add tests

TASK-831 Isolate object resolution code 

---

src/us/kbase/workspace/WorkspaceServer.java
src/us/kbase/workspace/database/Workspace.java
src/us/kbase/workspace/test/workspace/WorkspaceTest.java
src/us/kbase/workspace/test/workspace/WorkspaceTester.java

TASK-831 Add admin flag to get objects & get object info at Workspace level

---

Makefile
build.xml

Make a test-quick target

---

deploy.cfg.example
src/us/kbase/workspace/WorkspaceServer.java
src/us/kbase/workspace/database/Workspace.java
src/us/kbase/workspace/listener/WorkspaceEventListener.java
src/us/kbase/workspace/test/listener/BadListenerFactory.java
src/us/kbase/workspace/test/listener/NullListenerFactory.java
src/us/kbase/workspace/test/workspace/WorkspaceListenerTest.java
src/us/kbase/workspace/test/workspace/WorkspaceTest.java
src/us/kbase/workspace/test/workspace/WorkspaceTester.java

Also simplify the interface for the meta data altering methods.

TASK-833 Add workspace metadata change event to listener

---

src/us/kbase/workspace/database/ObjectIDNoWSNoVer.java
src/us/kbase/workspace/database/ObjectIDResolvedWS.java
src/us/kbase/workspace/database/ResolvedObjectID.java
src/us/kbase/workspace/database/ResolvedObjectIDNoVer.java
src/us/kbase/workspace/database/mongo/MongoWorkspaceDB.java
src/us/kbase/workspace/database/mongo/ObjectIDResolvedWSNoVer.java
src/us/kbase/workspace/database/mongo/ObjectInfoUtils.java
src/us/kbase/workspace/database/mongo/QueryMethods.java
src/us/kbase/workspace/database/mongo/ResolvedObjectID.java
src/us/kbase/workspace/database/mongo/ResolvedObjectIDNoVer.java
src/us/kbase/workspace/test/database/mongo/MongoInternalsTest.java
src/us/kbase/workspace/test/workspace/ObjectIdentifierTest.java
src/us/kbase/workspace/test/workspace/ResolvedObjectIdentifierTest.java

Were specific to the mongo implementation. Also various minor refactoring and tests.

Refactor various object identifier classes for reuse

---

deploy.cfg.example
docsource/releasenotes.rst
src/us/kbase/workspace/database/CopyResult.java
src/us/kbase/workspace/database/Workspace.java
src/us/kbase/workspace/database/WorkspaceDatabase.java
src/us/kbase/workspace/database/mongo/MongoWorkspaceDB.java
src/us/kbase/workspace/listener/WorkspaceEventListener.java
src/us/kbase/workspace/test/listener/BadListenerFactory.java
src/us/kbase/workspace/test/listener/NullListenerFactory.java
src/us/kbase/workspace/test/workspace/WorkspaceListenerTest.java

Adds the last 3 events - copy, un/delete objects, save objects.

Complete listener api

---

src/us/kbase/workspace/database/ResolvedWorkspaceID.java
src/us/kbase/workspace/database/Workspace.java
src/us/kbase/workspace/database/mongo/MongoWorkspaceDB.java
src/us/kbase/workspace/kbase/InitWorkspaceServer.java
src/us/kbase/workspace/listener/ListenerInitializationException.java
src/us/kbase/workspace/listener/WorkspaceEventListener.java
src/us/kbase/workspace/modules/RESKEPrototypeEventHandlerFactory.java
src/us/kbase/workspace/modules/package-info.java
src/us/kbase/workspace/test/listener/BadListenerFactory.java
src/us/kbase/workspace/test/listener/NullListenerFactory.java
src/us/kbase/workspace/test/workspace/WorkspaceListenerTest.java

Currently works for save objects.
TODO:

TASK-895 Add prototype RESKE event handler.

---

src/us/kbase/workspace/database/Workspace.java
src/us/kbase/workspace/listener/WorkspaceEventListener.java
src/us/kbase/workspace/modules/RESKEPrototypeEventHandlerFactory.java
src/us/kbase/workspace/test/listener/BadListenerFactory.java
src/us/kbase/workspace/test/listener/NullListenerFactory.java
src/us/kbase/workspace/test/workspace/WorkspaceListenerTest.java

TASK-895 copy all versions & clone events

---

src/us/kbase/workspace/modules/RESKEPrototypeEventHandlerFactory.java

Changes are in process RESKE side

TASK-895 Fix rename object event

---

src/us/kbase/workspace/modules/RESKEPrototypeEventHandlerFactory.java

Also fixes mongopwd retrieval from config

TASK-1046 Send type version to RESKE.

---

src/us/kbase/workspace/database/ObjectInfoWithModDate.java
src/us/kbase/workspace/database/Workspace.java
src/us/kbase/workspace/database/WorkspaceDatabase.java
src/us/kbase/workspace/database/mongo/MongoWorkspaceDB.java
src/us/kbase/workspace/listener/WorkspaceEventListener.java
src/us/kbase/workspace/modules/KnowledgeEnginePrototypeEventHandlerFactory.java
src/us/kbase/workspace/modules/RESKEPrototypeEventHandlerFactory.java
src/us/kbase/workspace/test/listener/BadListenerFactory.java
src/us/kbase/workspace/test/listener/NullListenerFactory.java
src/us/kbase/workspace/test/workspace/WorkspaceListenerTest.java

Set event timestamps to the time of the actual event since they're indexed.

TASK-1074 Fix event timestamps

---

src/us/kbase/workspace/modules/SearchPrototypeEventHandlerFactory.java

Match current version of search indexer.

TASK-1161 Update search listener

---

docsource/buildinitclient.rst

- references to latest jars
- updated code snippet for workspace client initialization using auth version 0.4.4

updated client init documentation

---

src/us/kbase/workspace/modules/SearchPrototypeEventHandlerFactory.java

@briehl - should definitely review
@arfathpasha - may be interested

SCT-58 Ignore temporary narratives re event generation

---

src/us/kbase/workspace/test/database/mongo/ShockBlobStoreIntegrationTest.java

Rename shock test to integration test

---

deploy.cfg.example
deployment/conf/.templates/deployment.cfg.templ
docsource/buildandconfigure.rst
docsource/developers.rst
docsource/releasenotes.rst
src/us/kbase/common/test/TestCommon.java
src/us/kbase/workspace/kbase/InitWorkspaceServer.java
src/us/kbase/workspace/kbase/KBaseWorkspaceConfig.java
src/us/kbase/workspace/test/kbase/HandleTest.java
src/us/kbase/workspace/test/kbase/JSONRPCLayerTester.java
src/us/kbase/workspace/test/kbase/LoggingTest.java
src/us/kbase/workspace/test/workspace/WorkspaceTester.java

First step for making ws admins based on auth2 roles
Tests pass locally

Replace globus url with auth2 url

---

.classpath
build.xml
deploy.cfg.example
deployment/services/workspace/README.md
docsource/administrationinterface.rst
src/us/kbase/common/test/TestCommon.java
src/us/kbase/workspace/database/UncheckedUserMetadata.java
src/us/kbase/workspace/database/Util.java
src/us/kbase/workspace/kbase/KBaseWorkspaceConfig.java
src/us/kbase/workspace/modules/KafkaNotifierFactory.java
src/us/kbase/workspace/test/modules/KafkaNotifierFactoryTest.java

Only saveObjects implemented for now.
TODO:
* Add more implementations
* Will require adding user to method sigs in most cases
* Document how to configure the notifier

Add rev 1 of Kafka notifier

---

Makefile

Fix docker build

---

src/us/kbase/common/service/ServiceChecker.java
src/us/kbase/workspace/database/mongo/MongoWorkspaceDB.java

The workspace counter stuff was especially goofy so I want to commit and
test
Also update the service checker to the python3 SDK service GET error
message

SCT-1770 Remove Jongo overlay part 1 of many

---

src/us/kbase/typedobj/db/MongoTypeStorage.java
src/us/kbase/typedobj/db/test/MongoTypeStorageTest.java
src/us/kbase/workspace/test/database/mongo/MongoWorkspaceDBTest.java

Added tests for uncovered code prior to changes

SCT-1770 continue removing Jongo layer from type database

---

src/us/kbase/typedobj/db/MongoTypeStorage.java
src/us/kbase/typedobj/db/test/MongoTypeStorageTest.java

Added test for uncovered code prior to making changes.

SCT-1770 continue removing Jongo from type database

---

src/us/kbase/typedobj/db/MongoTypeStorage.java
src/us/kbase/typedobj/db/test/MongoTypeStorageTest.java
src/us/kbase/workspace/kbase/InitWorkspaceServer.java
src/us/kbase/workspace/kbase/Settings.java

Added tests for uncovered code prior to changes.
Also remove from workspace initialization class.

SCT-1770 finish removing jongo from type database

---

src/us/kbase/workspace/kbase/KBaseWorkspaceConfig.java
src/us/kbase/workspace/test/kbase/KBaseWorkspaceConfigTest.java

Before we start making fairly large changes to it

Add tests for workspace config handler & clean up

---

build.xml
src/us/kbase/workspace/test/kbase/HandleAndShockTest.java

and we'll also test @id shock integration eventually

Change handle test to note we also test the Shock backend

---

.classpath
build.xml
src/us/kbase/typedobj/idref/IdReferenceHandlerSet.java
src/us/kbase/typedobj/idref/SimpleRemappedId.java
src/us/kbase/workspace/kbase/HandleIdHandlerFactory.java
src/us/kbase/workspace/kbase/ShockIdHandlerFactory.java
src/us/kbase/workspace/test/kbase/HandleAndShockTest.java
src/us/kbase/workspace/test/kbase/ShockIdHandlerFactoryTest.java

Kinda big, but 99% greenfield on 1 new file + tests
//TODO SHOCKID new params - shock url, shock user, shock token (toggle required based on shock url)
//TODO SHOCKID integrate into startup
//TODO SHOCKID integration tests
//TODO SHOCKID documentation, compare vs. handle ID (shock int docs, type @id docs)

Add shock ID handler

---

src/us/kbase/typedobj/core/Restreamable.java
src/us/kbase/typedobj/core/ValidatedTypedObject.java
src/us/kbase/typedobj/test/TypedObjectValidationReportTest.java
src/us/kbase/workspace/database/mongo/GridFSBlobStore.java
src/us/kbase/workspace/test/database/mongo/GridFSBlobStoreTest.java
src/us/kbase/workspace/test/database/mongo/ShockBlobStoreIntegrationTest.java
test/performance/ConfigurationsAndThreads.java

Will be required for talking to S3.
Also found and fixed a potential resource leak.

Add getSize() to Restreamable

---

build.xml
src/us/kbase/workspace/database/ByteArrayFileCacheManager.java
src/us/kbase/workspace/database/mongo/Fields.java
src/us/kbase/workspace/database/mongo/S3BlobStore.java
src/us/kbase/workspace/database/mongo/S3ClientWithPresign.java
src/us/kbase/workspace/database/mongo/ShockBlobStore.java
src/us/kbase/workspace/test/database/mongo/S3BlobStoreTest.java
src/us/kbase/workspace/test/database/mongo/ShockBlobStoreTest.java

Also found an unused method in ByteArrayFileCacheManager that would
cause a stack overflow if it was ever called and removed it.
TODO:
* integration tests
* integrate into workspace test & workspace long test
* add to config
* integrate into build and test manually

Add S3 blobstore implementation & unit tests

---

src/us/kbase/workspace/database/mongo/Fields.java
src/us/kbase/workspace/database/mongo/S3BlobStore.java
src/us/kbase/workspace/kbase/InitWorkspaceServer.java
src/us/kbase/workspace/test/database/mongo/S3BlobStoreIntegrationTest.java
src/us/kbase/workspace/test/database/mongo/S3BlobStoreTest.java

Since we're just going to port the shock nodes over into CEPH

S3 keys should be based on UUIDs, not MD5s

---

.classpath
.travis.yml
build.xml
docsource/administrationinterface.rst
docsource/releasenotes.rst
docsource/test.rst
docsource/typedobjects.rst
handle_service_test/Pipfile
handle_service_test/Pipfile.lock
shock_builds/kbase_fork/160815_e9f0e1618e265042bf5cb96429995b5e6ec0a06a/shock.cfg
src/us/kbase/workspace/WorkspaceServer.java
src/us/kbase/workspace/database/UserWorkspaceIDs.java
src/us/kbase/workspace/modules/KafkaNotifierFactory.java
src/us/kbase/workspace/test/controllers/handle/HandleServiceController.java
src/us/kbase/workspace/test/kbase/HandleAndShockTest.java
src/us/kbase/workspace/test/workspace/UserWorkspaceIDsTest.java
test.cfg.example

Added a Pipfile for easily creating a HS2 test environment.

Make tests pass locally & with java 11

---

docsource/events.rst
docsource/releasenotes.rst
docsource/typedobjects.rst
src/us/kbase/workspace/WorkspaceServer.java
src/us/kbase/workspace/database/mongo/MongoWorkspaceDB.java
src/us/kbase/workspace/modules/KafkaNotifierFactory.java
src/us/kbase/workspace/test/kbase/JSONRPCLayerTest.java
src/us/kbase/workspace/test/modules/KafkaNotifierFactoryTest.java

also some minor documentation fixes
Being a little bit lazy here and relying on unit tests. Once it's up in CI we can check if Kafka is getting the events.

Add workspace events to Kafka notifier

---

docsource/releasenotes.rst
src/us/kbase/workspace/WorkspaceServer.java
src/us/kbase/workspace/kbase/InitWorkspaceServer.java
src/us/kbase/workspace/kbase/ShockIdHandlerFactory.java
src/us/kbase/workspace/kbase/WorkspaceServerMethods.java

Now there's a status method, can just use that
Also move the check method into the server class. No point in putting it
in the methods class.

Stop spamming handle service logs

---

build.xml

Unused, build happens in travis now

Remove jenkins cruft from the build

---

deploy.cfg.example
deployment/conf/.templates/deployment.cfg.templ
docsource/buildandconfigure.rst
src/us/kbase/workspace/kbase/InitWorkspaceServer.java
src/us/kbase/workspace/kbase/KBaseWorkspaceConfig.java
src/us/kbase/workspace/test/kbase/HandleAndShockTest.java
src/us/kbase/workspace/test/kbase/KBaseWorkspaceConfigTest.java

Since it doesn't exist any more

Remove more handle manager cruft

---

src/us/kbase/typedobj/idref/IdReferenceHandlerSet.java
src/us/kbase/workspace/kbase/SampleIdHandlerFactory.java
src/us/kbase/workspace/test/kbase/SampleIDHandlerFactoryTest.java

Next steps:
* integrate into the workspace
* integration tests
* documentation
This is also on the big side, but it's 100% greenfield, standalone, and 2/3 test code, so hopefully not too hard to understand.

Add sample ID handler

---

src/us/kbase/workspace/test/controllers/sample/SampleServiceController.java

Writing a main() test method would require bringing up arango,
auth, and the workspace. Too much of a pain, tested in the integration
test rig that is currently local WIP.

Add sample service controller

---

src/us/kbase/typedobj/idref/IdReferenceType.java
src/us/kbase/typedobj/test/idref/IdReferenceTypeTest.java

Also minor clean up, documentation

Make IDReferenceType comparable, add tests

---

src/us/kbase/workspace/test/controllers/arango/ArangoController.java
src/us/kbase/workspace/test/kbase/SampleServiceIntegrationTest.java

Not clearing the Auth DB obviously, unnecessary and annoying

Clear DBs between tests

---

.classpath
build.xml
docsource/releasenotes.rst
performance/us/kbase/workspace/performance/shockclient/SaveAndGetFromShock.java
src/us/kbase/common/test/service/ServiceCheckerTest.java
src/us/kbase/workspace/database/mongo/ShockBlobStore.java
src/us/kbase/workspace/test/database/mongo/ShockBlobStoreIntegrationTest.java
src/us/kbase/workspace/test/database/mongo/ShockBlobStoreTest.java
src/us/kbase/workspace/test/docserver/DocServerTest.java
src/us/kbase/workspace/test/kbase/HandleAndShockTest.java
test/performance/ConfigurationsAndThreads.java

At this point in time, all commits in develop have been merged to master, so syncing master -> dev_candidate to bring in all dev & master changes

Sync master -> dev candidate

---

deploy.cfg.example
deployment/conf/.templates/deployment.cfg.templ
docsource/buildandconfigure.rst
docsource/releasenotes.rst
src/us/kbase/workspace/WorkspaceServer.java
src/us/kbase/workspace/database/mongo/S3ClientWithPresign.java
src/us/kbase/workspace/kbase/InitWorkspaceServer.java
src/us/kbase/workspace/kbase/KBaseWorkspaceConfig.java
src/us/kbase/workspace/test/database/mongo/S3BlobStoreIntegrationTest.java
src/us/kbase/workspace/test/kbase/JSONRPCLayerTest.java
src/us/kbase/workspace/test/kbase/KBaseWorkspaceConfigTest.java
src/us/kbase/workspace/test/workspace/WorkspaceTester.java

Includes the S3 backend self signed cert option.

Sync develop -> dev-candidate

---

docsource/developers.rst

Also clarify when and how version formats should be used

More dev-candidate purging

---

.travis.yml
docsource/buildandconfigure.rst

Complete waste of time
Also update to latest version of Mongo 3.6

Stop testing against Mongo 2.X

---

docsource/events.rst
docsource/releasenotes.rst
src/us/kbase/workspace/listener/WorkspaceEventListener.java
src/us/kbase/workspace/modules/KafkaNotifierFactory.java
src/us/kbase/workspace/test/listener/BadListenerFactory.java
src/us/kbase/workspace/test/listener/NullListenerFactory.java
src/us/kbase/workspace/test/modules/KafkaNotifierFactoryTest.java

Nothing actually calls the new method yet, that'll happen in future PRs

Hide object notifications part 2: Add a hide event to the event listener framework

---

src/us/kbase/workspace/database/mongo/MongoWorkspaceDB.java
src/us/kbase/workspace/test/database/mongo/MongoWorkspaceDBTest.java

Actually test deletion update times

---

docsource/releasenotes.rst
src/us/kbase/workspace/database/WorkspaceDatabase.java
src/us/kbase/workspace/database/mongo/MongoWorkspaceDB.java
src/us/kbase/workspace/test/database/mongo/MongoWorkspaceDBTest.java

Needed for event handling, which requires a time.

Return object modification times on a hide call

---

src/us/kbase/workspace/database/mongo/MongoWorkspaceDB.java
src/us/kbase/workspace/database/mongo/ObjectInfoUtils.java
src/us/kbase/workspace/database/mongo/ObjectLister.java

Easier to understand separation between the functions if they're in different modules
No behavioral changes

Split out object listing code from general object utils

---

src/us/kbase/workspace/test/workspace/PermissionSetTest.java

Fix test name

---

src/us/kbase/workspace/database/ListObjectsParameters.java
src/us/kbase/workspace/database/mongo/Fields.java
src/us/kbase/workspace/database/mongo/MongoWorkspaceDB.java
src/us/kbase/workspace/database/mongo/ObjectInfoUtils.java
src/us/kbase/workspace/database/mongo/ObjectLister.java
src/us/kbase/workspace/test/database/mongo/GridFSBlobStoreTest.java
src/us/kbase/workspace/test/database/mongo/MongoInternalsTest.java
src/us/kbase/workspace/test/database/mongo/MongoStartUpTest.java
src/us/kbase/workspace/test/database/mongo/S3BlobStoreIntegrationTest.java

Needed to enable paging objects while filtering on type

Add new type fields and indexes

---

src/us/kbase/workspace/test/database/mongo/MongoWorkspaceDBTest.java
src/us/kbase/workspace/test/database/mongo/PartialMock.java

Designed for use with the PartialMock set up so added to that class

Extract test object save helper method for reuse

---

performance/us/kbase/workspace/performance/workspace/Common.java
src/us/kbase/workspace/database/mongo/MongoWorkspaceDB.java
src/us/kbase/workspace/test/workspace/WorkspaceConstructorTest.java

Minor cleanup from notes in https://github.com/kbase/workspace_deluxe/pull/460 and a couple other items

Minor text cleanup

---

docsource/developers.rst
src/us/kbase/workspace/WorkspaceServer.java
src/us/kbase/workspace/version/WorkspaceVersion.java

vs bundled in the server class. Will be needed for the schema updater
CLI.

Move version to a standalone class

---

src/us/kbase/common/test/TestCommon.java
src/us/kbase/workspace/WorkspaceServer.java
src/us/kbase/workspace/kbase/KBaseWorkspaceConfig.java
src/us/kbase/workspace/test/kbase/KBaseWorkspaceConfigTest.java

The server super class basically takes care of this for the workspace
server, but that doesn't help if you want to load the config without the
server running

Support loading config from a file

---

LICENSE.md
build.xml
src/us/kbase/workspace/database/ListObjectsParameters.java

Tested manually.
Also update license

Add wrapper script for the schema upgrader

---

src/us/kbase/workspace/database/RefLimit.java
src/us/kbase/workspace/database/mongo/MongoWorkspaceDB.java

JIT Optionals for RefLimit class

---

src/us/kbase/workspace/database/RefLimit.java
src/us/kbase/workspace/test/workspace/RefLimitTest.java

Step 1 of doing the stupid ref math serverside instead of making the
user do it

Add version decrementation to RefLimit

---

.travis.yml
docsource/conf.py

dev-gavin-incoming -> develop

---

src/us/kbase/workspace/database/ByteArrayFileCacheManager.java
src/us/kbase/workspace/database/Workspace.java
src/us/kbase/workspace/database/mongo/MongoWorkspaceDB.java
src/us/kbase/workspace/database/mongo/QueryMethods.java

Did this almost absentmindedly while looking for ways to speed up result tab rendering.
I'm just going straight to develop because I don't care about having an image built from this PR.

Trivial code cleanup

---

src/us/kbase/workspace/database/ObjectIDNoWSNoVer.java
src/us/kbase/workspace/test/workspace/ObjectIDNoWSNoVerTest.java

Better to keep 1 test class per class under test than merge multiple
classes into on test class

DATAUP-725: Return the object name from the name check method, rename test

---

src/us/kbase/common/test/TestCommon.java
src/us/kbase/workspace/database/ObjectIdentifier.java
src/us/kbase/workspace/test/LongTextForTestUsage.java
src/us/kbase/workspace/test/workspace/ObjectIdentifierTest.java
src/us/kbase/workspace/test/workspace/WorkspaceLongTest.java
src/us/kbase/workspace/test/workspace/WorkspaceTest.java
src/us/kbase/workspace/test/workspace/WorkspaceTester.java

Next:
* Hide the 2 inner classes and delete all public constructors and create
methods
* Add unit tests for the rest of the class
* Handle any remaining NOW TODOs in the class

DATAUP-725: Add an ObjectIdentifier builder

---

src/us/kbase/workspace/database/ObjectIdentifier.java
src/us/kbase/workspace/test/workspace/ObjectIdentifierTest.java

DATAUP-725: Add a ObjectIdentifier.Builder copy method.

---

src/us/kbase/common/test/TestCommon.java
src/us/kbase/workspace/database/ObjectIdentifier.java
src/us/kbase/workspace/database/ObjectReferenceSet.java
src/us/kbase/workspace/database/ObjectResolver.java
src/us/kbase/workspace/database/Reference.java
src/us/kbase/workspace/database/exceptions/NoSuchReferenceException.java
src/us/kbase/workspace/test/kbase/IdentifierUtilsTest.java
src/us/kbase/workspace/test/workspace/ObjectIdentifierTest.java
src/us/kbase/workspace/test/workspace/WorkspaceLongTest.java

Avoid the billion dollar mistake

DATAUP-725: Return Optionals vs. nulls from ObjectIdentifier API

---

src/us/kbase/workspace/database/ObjectIdentifier.java
src/us/kbase/workspace/database/ObjectInformation.java
src/us/kbase/workspace/database/WorkspaceObjectData.java
src/us/kbase/workspace/database/mongo/ObjectIDResolvedWSNoVer.java

and make it a package only class, since that's the only place it's used.

DATAUP-725: Delete unused code in an internal class

---

src/us/kbase/workspace/WorkspaceServer.java
src/us/kbase/workspace/database/Workspace.java
src/us/kbase/workspace/database/WorkspaceObjectData.java
src/us/kbase/workspace/kbase/ArgUtils.java
src/us/kbase/workspace/test/database/mongo/MongoWorkspaceDBTest.java
src/us/kbase/workspace/test/workspace/WorkspaceLongTest.java
src/us/kbase/workspace/test/workspace/WorkspaceObjectDataTest.java
src/us/kbase/workspace/test/workspace/WorkspaceTest.java
src/us/kbase/workspace/test/workspace/WorkspaceTester.java
test/performance/GetObjectsLibSpeedTest.java

Avoid the billion dollar mistake

DATAUP-725: Use Optionals vs nulls in WorkspaceObjectBuilder

---

performance/us/kbase/workspace/performance/refsearch/GetReferencedObjectWithBFS.java
performance/us/kbase/workspace/performance/refsearch/v0_3_5/GetReferencedObjectWithBFS.java
src/us/kbase/workspace/WorkspaceServer.java
src/us/kbase/workspace/database/Workspace.java
src/us/kbase/workspace/test/workspace/WorkspaceLongTest.java
src/us/kbase/workspace/test/workspace/WorkspaceTest.java
src/us/kbase/workspace/test/workspace/WorkspaceTester.java
src/us/kbase/workspace/test/workspace/WorkspaceUnitTest.java
test/performance/GetObjectsLibSpeedTest.java

DATAUP-725: Limit getObjects to 10K objects at a time

---

src/us/kbase/workspace/database/DynamicConfig.java
src/us/kbase/workspace/test/workspace/DynamicConfigTest.java

Next: plumb it through the administration interface to the mongo layer, adding get and set methods

DATAUP-725: Add dynamic configuration class (#2/11)

---

src/us/kbase/workspace/database/mongo/GridFSBlobStore.java
src/us/kbase/workspace/database/mongo/S3BlobStore.java
src/us/kbase/workspace/database/mongo/exceptions/NoSuchBlobException.java
src/us/kbase/workspace/test/database/mongo/GridFSBlobStoreTest.java
src/us/kbase/workspace/test/database/mongo/MongoWorkspaceDBTest.java
src/us/kbase/workspace/test/database/mongo/S3BlobStoreTest.java

Will shortly be thrown from a thead and the MD5 will be needed outside
the thread context

DATAUP-725: Include blob MD5 in NoSuchBlobException (#7/11)

---

src/us/kbase/typedobj/test/DummyValidatedTypedObject.java
src/us/kbase/workspace/database/Workspace.java
src/us/kbase/workspace/database/WorkspaceDatabase.java
src/us/kbase/workspace/database/mongo/MongoWorkspaceDB.java
src/us/kbase/workspace/kbase/WorkspaceServerMethods.java
src/us/kbase/workspace/test/database/mongo/MongoWorkspaceDBTest.java
src/us/kbase/workspace/test/workspace/WorkspaceUnitTest.java

TODO:
* Hook up the dynamic config to the parallelization code
* Add documentation

DATAUP-725: Parallelize fetching data from the blob backend (#8/11)

---

src/us/kbase/workspace/database/Workspace.java
src/us/kbase/workspace/test/kbase/JSONRPCLayerTest.java
src/us/kbase/workspace/test/kbase/JSONRPCLayerTester.java
src/us/kbase/workspace/test/kbase/LoggingTest.java
src/us/kbase/workspace/test/kbase/SampleServiceIntegrationTest.java
src/us/kbase/workspace/test/workspace/WorkspaceTester.java
src/us/kbase/workspace/test/workspace/WorkspaceUnitTest.java

Not really sure how to test this further. The scaling factor doesn't
change any visible behavior other than, possibly, the time it takes for
the method to run, and depending on the test environment that may not be
significant.

DATAUP-725: Pass the configured scaling factor to the data fetch method (#9/11)

---

docsource/upgrades.rst

Closes https://github.com/kbase/workspace_deluxe/issues/511

Add version 0.13.0 to the upgrade guide

---

docsource/upgrades.rst

* Update release notes and force GHA build

Update release notes and force GHA build

---

src/us/kbase/workspace/test/controllers/blobstore/BlobstoreController.java

...to replace the Shock controller

Add a Blobstore controller

---

.classpath
build.xml

Has some features I'm going to want to use for the provenance changes

PTV-1773: Update mongo java driver

---

docsource/releasenotes.rst
src/us/kbase/workspace/database/provenance/Common.java
src/us/kbase/workspace/database/provenance/ExternalData.java
src/us/kbase/workspace/database/provenance/Provenance.java
src/us/kbase/workspace/database/provenance/ProvenanceAction.java
src/us/kbase/workspace/database/provenance/SubAction.java
src/us/kbase/workspace/kbase/ArgUtils.java
src/us/kbase/workspace/kbase/WorkspaceServerMethods.java
src/us/kbase/workspace/test/database/provenance/ExternalDataTest.java
src/us/kbase/workspace/test/database/provenance/SubActionTest.java
src/us/kbase/workspace/test/kbase/ArgUtilsTest.java
src/us/kbase/workspace/test/kbase/JSONRPCLayerTest.java
src/us/kbase/workspace/test/kbase/JSONRPCLayerTester.java

Tell the user where the error is in the data structure

PTV-1733 Improve provenance & general object error handling

---

src/us/kbase/workspace/test/kbase/JSONRPCLayerTest.java
src/us/kbase/workspace/test/kbase/SchemaUpdaterCLITest.java
src/us/kbase/workspace/version/WorkspaceVersion.java

Bump version (incoming -> develop)

---

docsource/releasenotes.rst
src/us/kbase/workspace/test/kbase/JSONRPCLayerTest.java
src/us/kbase/workspace/test/kbase/SchemaUpdaterCLITest.java
src/us/kbase/workspace/version/WorkspaceVersion.java

Update version and release notes for 0.13.0 release

---

src/us/kbase/workspace/kbase/InitWorkspaceServer.java
src/us/kbase/workspace/kbase/WorkspaceServerMethods.java
src/us/kbase/workspace/kbase/admin/AdministrationCommandSetBuilder.java
src/us/kbase/workspace/kbase/admin/WorkspaceAdministration.java
src/us/kbase/workspace/test/kbase/admin/WorkspaceAdministrationWithHandlersTest.java

Still needs unit tests but that'd add 600+ lines to the commit. Will add unit tests in the next PR.
Also contains some code cleanup.

PTV-1786: Add a builder for the administration interface

---

src/us/kbase/workspace/kbase/admin/WorkspaceAdministration.java
src/us/kbase/workspace/test/kbase/admin/WorkspaceAdministrationTest.java
src/us/kbase/workspace/test/kbase/admin/WorkspaceAdministrationWithHandlersTest.java

Moved WorkspaceAdministration specific tests from `WorkspaceAdministrationWithHandlersTest` to the new unit tests

PTV-1786: Add unit tests for WorkspaceAdministration

---

src/us/kbase/workspace/kbase/InitWorkspaceServer.java
src/us/kbase/workspace/kbase/admin/AdministrationCommandSetInstaller.java
src/us/kbase/workspace/test/kbase/admin/AdministrationCommandSetInstallerTest.java

More accurately describes what it does

PTV-1786: Rename the command set installer

---

src/us/kbase/workspace/WorkspaceServer.java
src/us/kbase/workspace/kbase/InitWorkspaceServer.java
src/us/kbase/workspace/kbase/LocalTypeServerMethods.java
src/us/kbase/workspace/kbase/WorkspaceServerMethods.java
src/us/kbase/workspace/kbase/admin/AdministrationCommandSetInstaller.java
src/us/kbase/workspace/test/kbase/admin/AdministrationCommandSetInstallerTest.java

Will allow creating an interface and alternate implementation that delegates to another workspace service

PTV-1786: Extract type methods from the server class into their own class

---

src/us/kbase/typedobj/core/TypeProvider.java
src/us/kbase/typedobj/core/TypedObjectValidator.java
src/us/kbase/workspace/database/Workspace.java
src/us/kbase/workspace/test/kbase/JSONRPCLayerTest.java
src/us/kbase/workspace/test/workspace/WorkspaceTest.java
src/us/kbase/workspace/test/workspace/WorkspaceUnitTest.java

In preparation for delgating type provider implementation

PTV-1786: Add type fetch exception to type provider

---

src/us/kbase/workspace/kbase/DelegatingTypeProvider.java
src/us/kbase/workspace/test/kbase/DelegatingTypeProviderTest.java

In some cases supplying an absolute type ID could return newer type info than a non-absolute ID, which should be impossible

PTV-1786: Fix delegating type provider inconsistency bug

---

src/us/kbase/workspace/kbase/KBaseWorkspaceConfig.java
src/us/kbase/workspace/test/kbase/KBaseWorkspaceConfigTest.java

Undocumented and unused for now

PTV-1786: Add type-delegation-target to workspace config

---

src/us/kbase/workspace/kbase/InitWorkspaceServer.java
src/us/kbase/workspace/test/kbase/JSONRPCLayerTester.java
src/us/kbase/workspace/test/kbase/TypeDelegationTest.java

Only a couple basic tests for now, will add more integration tests in future PRs

PTV-1786: Integrate type delegation code in the workspace builder class

---

src/us/kbase/workspace/test/kbase/TypeDelegationTest.java

As the class docs say, these are not exhaustive tests - they just check the delegation works.

PTV-1786: Add tests that exercise the standard type delegation functions.

---

src/us/kbase/workspace/database/provenance/Organization.java
src/us/kbase/workspace/test/database/provenance/OrganizationTest.java

Adding in the Organisation object that will be used in the credit metadata.
Per the schema:
organizationName: string, required
organizationID: string, optional

CE-93: add organization class

---

src/us/kbase/common/test/TestCommon.java
src/us/kbase/workspace/database/Util.java
src/us/kbase/workspace/test/database/UtilTest.java

The other pull request for CE-94 (#636) will add a method to the Util class, and since said class does not have any tests yet, I have taken the liberty of adding some. I will complete #636 once the content of this PR has been merged.

WIP CE-94: adding tests for us.kbase.workspace.database.Util

---

src/us/kbase/common/test/service/ServiceCheckerTest.java

Switching tests over to CI whilst next is kaput

---

src/us/kbase/workspace/database/provenance/FundingReference.java
src/us/kbase/workspace/test/database/provenance/FundingReferenceTest.java

Funding reference class:
- funderName: string, required
- funderID: string, PID format, optional
- awardID: string, may or may not be in PID format, optional
- awardTitle: string, optional
- awardURI: URL, optional
This PR needs #639 to be merged first so that the tests will pass.

CE-97: Funding Reference class

---

src/us/kbase/workspace/database/provenance/PermanentID.java
src/us/kbase/workspace/database/provenance/RelationshipType.java
src/us/kbase/workspace/test/database/provenance/PermanentIDTest.java
src/us/kbase/workspace/test/database/provenance/RelationshipTypeTest.java

Converting the previously stringiform "relationshipType" field into a proper enum.

CE-94: relationships

---

src/us/kbase/workspace/database/provenance/Common.java
src/us/kbase/workspace/database/provenance/RelationshipType.java
src/us/kbase/workspace/test/database/provenance/PermanentIDTest.java
src/us/kbase/workspace/test/database/provenance/RelationshipTypeTest.java

Adding in Crossref relationship types

CE-94: Adding in the Crossref relationship types

---

workspace.spec

Zero content changes, all trailing whitespace removal.

Removing trailing whitespace from spec file

---

src/us/kbase/workspace/kbase/ArgUtils.java

The ArgUtils file will also be edited as part of this project, so doing the trailing whitespace removal here, too.

Remove trailing whitespace

---

src/us/kbase/workspace/database/provenance/EventDate.java
src/us/kbase/workspace/test/database/provenance/EventDateTest.java
src/us/kbase/workspace/test/database/provenance/EventTest.java

Collect errors instead of emitting them one at a time.

CE-95: Retrofitting error collection and adding tests

---

.github/workflows/test.yml
src/us/kbase/workspace/database/provenance/Organization.java
src/us/kbase/workspace/test/database/provenance/OrganizationTest.java

As title, plus rename the test workflow.

CE-93: Updating organization validation to collect all errors at once

---

src/us/kbase/workspace/database/provenance/PermanentID.java
src/us/kbase/workspace/database/provenance/RelationshipType.java
src/us/kbase/workspace/test/database/provenance/OrganizationTest.java
src/us/kbase/workspace/test/database/provenance/PermanentIDTest.java
src/us/kbase/workspace/test/database/provenance/RelationshipTypeTest.java

Also entabbed some whitespace and updated the name of the class in which all this info will be held.

CE-94: Collecting PID errors, rather than reporting them one at a time

---

.classpath
build.xml

Hopefully will fix the post test class mongo cleanup errors
Fixes https://github.com/kbase/workspace_deluxe/issues/554

Update kbase-common jar

---

src/us/kbase/workspace/database/provenance/FundingReference.java
src/us/kbase/workspace/test/database/provenance/FundingReferenceTest.java

Another bit of error collation fun with standard disclaimer about greater maintenance burden, etc.

CE-97: funding ref error collation

---

build.xml
src/us/kbase/workspace/database/provenance/Title.java
src/us/kbase/workspace/test/database/provenance/TitleTest.java

Fields:
`titleString` - required
`titleType` - optional, enum
`titleLanguage` - optional

CE-96: title class

---

src/us/kbase/workspace/database/provenance/Title.java
src/us/kbase/workspace/test/database/provenance/TitleTest.java

ensure titleLanguage is specified if titleType is translated_title

CE-151: add title language constraint

---

src/us/kbase/workspace/test/kbase/ArgUtilsTest.java

Removing a load of trailing whitespace before I start doing anything with `ArgUtilsTest.java`.

CE-151: Removing lots of whitespace

---

src/us/kbase/workspace/database/provenance/PermanentID.java
workspace.spec

A start on writing up the workspace spec for the new classes. I anticipate this will require some back and forth, and once the wording looks OK, I will sort out the layout and add in the autogenerated classes.
The specs cover three classes that have not yet been added under `us.kbase.workspace.database.provenance`; this is deliberate as they are more complex and I want to look at how they will be created/manipulated in `ArgUtils` when I add them.

First draft of workspace spec

---

.github/workflows/test.yml
src/us/kbase/workspace/database/provenance/Common.java
src/us/kbase/workspace/database/provenance/Contributor.java
src/us/kbase/workspace/database/provenance/ContributorRole.java
src/us/kbase/workspace/test/database/provenance/ContributorRoleTest.java
src/us/kbase/workspace/test/database/provenance/ContributorTest.java

Fields:
`contributorType`: mandatory, either PERSON or ORGANIZATION
`name`: mandatory
`creditName`: optional; for special snowflakes and other people who want their name to appear in a certain format in a citation.
`contributorId`: optional
`affiliations`: list of `Organization`s; can be null/empty
`contributorRole`: list of `ContributorRole`s; can be null/empty

CE-98: contributor and contributor role

---

src/us/kbase/workspace/database/mongo/MongoWorkspaceDB.java
src/us/kbase/workspace/kbase/admin/AdministrationCommandSetInstaller.java
src/us/kbase/workspace/test/database/mongo/MongoWorkspaceDBTest.java

I anticipate having to edit these files so opened and saved them in my IDE to remove trailing whitespace. No other changes.

CE-?? - Removing trailing whitespace from files

---

src/us/kbase/typedobj/db/MongoTypeStorage.java
src/us/kbase/typedobj/db/test/MongoTypeStorageTest.java
src/us/kbase/typedobj/db/test/TypeRegisteringTest.java
src/us/kbase/workspace/test/database/mongo/GridFSBlobStoreTest.java
src/us/kbase/workspace/test/database/mongo/MongoInternalsTest.java
src/us/kbase/workspace/test/database/mongo/MongoStartUpTest.java
src/us/kbase/workspace/test/database/mongo/ObjectListerTest.java
src/us/kbase/workspace/test/database/mongo/PartialMock.java
src/us/kbase/workspace/test/database/mongo/S3BlobStoreIntegrationTest.java
src/us/kbase/workspace/test/database/mongo/S3BlobStoreTest.java
src/us/kbase/workspace/test/database/mongo/SchemaUpdaterTest.java
src/us/kbase/workspace/test/kbase/HandleAndBytestreamIntegrationTest.java
src/us/kbase/workspace/test/kbase/JSONRPCLayerLongTest.java
src/us/kbase/workspace/test/kbase/JSONRPCLayerTest.java
src/us/kbase/workspace/test/kbase/JSONRPCLayerTester.java
src/us/kbase/workspace/test/kbase/LoggingTest.java
src/us/kbase/workspace/test/kbase/SampleServiceIntegrationTest.java
src/us/kbase/workspace/test/kbase/TypeDelegationTest.java
src/us/kbase/workspace/test/workspace/WorkspaceIntegrationWithGridFSTest.java
src/us/kbase/workspace/test/workspace/WorkspaceLongTest.java
src/us/kbase/workspace/test/workspace/WorkspaceTest.java
src/us/kbase/workspace/test/workspace/WorkspaceTester.java

These files will be edited as when converting the workspace to gradle, so they require the whitespace to be removed.

Whitespace removal

---

src/us/kbase/workspace/test/database/provenance/ContributorRoleTest.java
src/us/kbase/workspace/test/database/provenance/ContributorTest.java
src/us/kbase/workspace/test/database/provenance/CreditMetadataTest.java
src/us/kbase/workspace/test/database/provenance/EventDateTest.java
src/us/kbase/workspace/test/database/provenance/EventTest.java
src/us/kbase/workspace/test/database/provenance/ExternalDataTest.java
src/us/kbase/workspace/test/database/provenance/FundingReferenceTest.java
src/us/kbase/workspace/test/database/provenance/OrganizationTest.java
src/us/kbase/workspace/test/database/provenance/PermanentIDTest.java
src/us/kbase/workspace/test/database/provenance/RelationshipTypeTest.java
src/us/kbase/workspace/test/database/provenance/TitleTest.java

It was pointless, but once I started I just couldn't stop.

CE-100: ordered imports

---

src/us/kbase/workspace/database/provenance/CreditMetadataEntry.java
src/us/kbase/workspace/test/database/provenance/CreditMetadataEntryTest.java

The long-awaited CreditMetadataEntry class!

CE-100: Adding CreditMetadataEntry class

---

src/us/kbase/workspace/Contributor.java
src/us/kbase/workspace/CreditMetadata.java
src/us/kbase/workspace/CreditMetadataEntry.java
src/us/kbase/workspace/EventDate.java
src/us/kbase/workspace/FundingReference.java
src/us/kbase/workspace/Organization.java
src/us/kbase/workspace/PermanentID.java
src/us/kbase/workspace/Title.java

Autogenerated classes for credit metadata, as generated by everyone's favourite compiler, kb-sdk.

CE-151: Adding kb-sdk-generated classes for credit metadata

---

src/us/kbase/workspace/database/mongo/MongoWorkspaceDB.java
src/us/kbase/workspace/test/database/mongo/MongoInternalsTest.java
src/us/kbase/workspace/test/database/mongo/MongoWorkspaceDBTest.java

with object version documents as well as workspace documents

Refactor metadata setting code for reuse

---

src/us/kbase/workspace/database/ObjectInformation.java
src/us/kbase/workspace/test/workspace/ObjectInformationTest.java

Will help a lot with some tests I'm writing

Add build from ObjectInformation method

---

src/us/kbase/workspace/database/Workspace.java
src/us/kbase/workspace/database/WorkspaceDatabase.java
src/us/kbase/workspace/database/mongo/MongoWorkspaceDB.java
src/us/kbase/workspace/test/database/mongo/MongoWorkspaceDBTest.java
src/us/kbase/workspace/test/workspace/WorkspaceUnitTest.java

Return resolved objects from set admin data methods

---

build.gradle
lib/Bio/KBase/workspace/Client.pm
lib/biokbase/workspace/client.py
lib/javascript/workspace/Client.js
src/us/kbase/workspace/WorkspaceClient.java

Also switch the default url to CI

Add kb-sdk compile tasks
