RELEASE_NOTES.txt, src/us/kbase/typedobj/core/JsonDocumentLocation.java, src/us/kbase/workspace/WorkspaceServer.java, src/us/kbase/workspace/database/mongo/MongoWorkspaceDB.java, src/us/kbase/workspace/database/mongo/QueryMethods.java, src/us/kbase/workspace/test/database/mongo/MongoInternalsTest.java, src/us/kbase/workspace/test/kbase/JSONRPCLayerTest.java, src/us/kbase/workspace/test/workspace/WorkspaceTest.java
This can wait for deploy until March, but I found some of these during JGI testing so I'm fixing them now.
Fixes:
Empty strings being rejected as map keys
NPE when calling get ref counts with a non-existant object version
Race conditions when simultaneously operating on and saving an object
=> Several bugfixes, some found in JGI testing

RELEASE_NOTES.txt, lib/Bio/KBase/workspace/Client.pm, src/us/kbase/workspace/WorkspaceClient.java, src/us/kbase/workspace/WorkspaceServer.java, src/us/kbase/workspace/database/Workspace.java, src/us/kbase/workspace/test/kbase/JSONRPCLayerTest.java, src/us/kbase/workspace/test/workspace/WorkspaceTest.java, src/us/kbase/workspace/test/workspace/WorkspaceTester.java, workspace.spec
Authentication blocks cause bugs - too easy to move or create a function in the wrong place.
Caused get_permissions* to go from auth required -> optional.
Fixed library function to allow null users and added tests.
=> Make all typespec auth declarations explicit

docsource/releasenotes.rst, src/us/kbase/workspace/kbase/WorkspaceAdministration.java, src/us/kbase/workspace/test/kbase/LoggingTest.java
Add logging to the administer() function beyond that automatically provided in JsonServerServlet. Logs which subfunction was called, and in most cases, the arguments to the subfunction.
Also add tests for existing application logging.
=> Improve admin logging

Makefile, docsource/releasenotes.rst, lib/Bio/KBase/workspace/Client.pm, src/us/kbase/workspace/ExternalDataUnit.java, src/us/kbase/workspace/ListObjectsParams.java, src/us/kbase/workspace/ListWorkspaceInfoParams.java, src/us/kbase/workspace/ObjectData.java, src/us/kbase/workspace/ObjectProvenanceInfo.java, src/us/kbase/workspace/ProvenanceAction.java, src/us/kbase/workspace/WorkspaceServer.java, src/us/kbase/workspace/database/Provenance.java, src/us/kbase/workspace/kbase/ArgUtils.java, src/us/kbase/workspace/kbase/WorkspaceServerMethods.java, src/us/kbase/workspace/test/kbase/JSONRPCLayerTest.java, src/us/kbase/workspace/test/kbase/JSONRPCLayerTester.java, workspace.spec
All incoming timestamps can be alternately supplied as Unix epochs.
Where possible (e.g. not tuples) epochs are provided as well as timestamps.
Also made kb-sdk compile targets.
=> Accept and emit Unix epoch times where possible

docsource/knownuserbugs.rst, docsource/releasenotes.rst, src/us/kbase/workspace/ListObjectsParams.java, src/us/kbase/workspace/WorkspaceClient.java, src/us/kbase/workspace/WorkspaceServer.java, src/us/kbase/workspace/database/GetObjectInformationParameters.java, src/us/kbase/workspace/database/ListObjectsParameters.java, src/us/kbase/workspace/database/Workspace.java, src/us/kbase/workspace/database/mongo/ObjectInfoUtils.java, src/us/kbase/workspace/test/kbase/JSONRPCLayerTest.java, src/us/kbase/workspace/test/kbase/JSONRPCLayerTester.java, src/us/kbase/workspace/test/workspace/WorkspaceLongTest.java, src/us/kbase/workspace/test/workspace/WorkspaceTest.java, src/us/kbase/workspace/test/workspace/WorkspaceTester.java, workspace.spec
Skip has all sorts of bad behavior associated with it which has been
discussed ad nauseum
LROC is not really useful generally - this type of thing should be done
in the nightly metrics, if at all. Also, the current plan for GC (if we
ever get around to it) would make the current implementation break, and
alternate implementations would be much slower.
=> Remove skip, deprecate list_referencing_object_counts

build.xml, docsource/releasenotes.rst, src/us/kbase/workspace/WorkspaceServer.java, src/us/kbase/workspace/database/DependencyStatus.java, src/us/kbase/workspace/database/Workspace.java, src/us/kbase/workspace/database/WorkspaceDatabase.java, src/us/kbase/workspace/database/mongo/BlobStore.java, src/us/kbase/workspace/database/mongo/GridFSBlobStore.java, src/us/kbase/workspace/database/mongo/MongoWorkspaceDB.java, src/us/kbase/workspace/database/mongo/ShockBlobStore.java, src/us/kbase/workspace/test/database/mongo/GridFSBlobStoreTest.java, src/us/kbase/workspace/test/database/mongo/ShockBlobStoreTest.java, src/us/kbase/workspace/test/workspace/WorkspaceTest.java
As opposed to a non-useful method.
Checks status of dependencies.
```
~$ curl -X POST -d '{"id": '1', "method": "Workspace.status", "version": "1.1", "params": []}' http://localhost:41670
{"version":"1.1","result":[{"state":"OK","message":"OK","dependencies":[{"name":"MongoDB","state":"OK","message":"OK","version":"2.4.14"},{"name":"GridFS","state":"OK","message":"OK","version":"2.4.14"}],"version":"0.5.0-dev2","git_url":"https://github.com/kbase/workspace_deluxe"}]}
~$ curl -X POST -d '{"id": '1', "method": "Workspace.status", "version": "1.1", "params": []}' http://localhost:41670
{"version":"1.1","result":[{"state":"Fail","message":"Dependency failure","dependencies":[{"name":"MongoDB","state":"Fail","message":"Couldn't connect to MongoDB: Timed out after 10000 ms while waiting to …
```
=> Add useful status method

build.xml, src/us/kbase/typedobj/core/TypedObjectValidator.java, src/us/kbase/typedobj/core/ValidatedTypedObject.java, src/us/kbase/typedobj/test/BasicValidationTest.java, src/us/kbase/typedobj/test/DetailedValidationTest.java, src/us/kbase/typedobj/test/DummyValidatedTypedObject.java, src/us/kbase/typedobj/test/IdProcessingTest.java, src/us/kbase/typedobj/test/JsonTokenValidatorTester.java, src/us/kbase/typedobj/test/MetadataExtractionTest.java, src/us/kbase/typedobj/test/ProfileBasicValidation.java, src/us/kbase/typedobj/test/TypedObjectValidationReportTest.java, src/us/kbase/workspace/database/ResolvedSaveObject.java, src/us/kbase/workspace/database/Workspace.java, src/us/kbase/workspace/database/WorkspaceSaveObject.java, src/us/kbase/workspace/database/mongo/GridFSBlobStore.java, src/us/kbase/workspace/database/mongo/ShockBlobStore.java, src/us/kbase/workspace/test/database/mongo/MongoInternalsTest.java
Requires https://github.com/kbase/jars/pull/41.
Renamed TypedObjectValidationReport -> ValidatedTypedObject
Removed a number of unnecessary stream buffers. JsonTokenStream, Jackson, and the JSON sorters all do their own buffering.
Add a buffer when necessary when calling ValidatedTypedObject.getInputStream().
Simplifies pulling data from Shock and as such removes the now unnecessary EasyStream library.
=> Clean up ValidatedTypedObject, remove EasyStream

src/us/kbase/common/service/ServiceChecker.java
Currently failing in CI because the handle manger is returning a field
that wasn't returned in my local copy of the handle manager (which might
be old).
=> Bugfix service checker - ignore unknown response properties.

docsource/releasenotes.rst, src/us/kbase/workspace/WorkspaceServer.java, src/us/kbase/workspace/database/ByteArrayFileCacheManager.java, src/us/kbase/workspace/database/Workspace.java, src/us/kbase/workspace/database/WorkspaceDatabase.java, src/us/kbase/workspace/database/WorkspaceObjectData.java, src/us/kbase/workspace/database/mongo/MongoWorkspaceDB.java, src/us/kbase/workspace/kbase/ArgUtils.java, src/us/kbase/workspace/test/database/mongo/MongoInternalsTest.java, src/us/kbase/workspace/test/workspace/WorkspaceLongTest.java, src/us/kbase/workspace/test/workspace/WorkspaceTest.java, src/us/kbase/workspace/test/workspace/WorkspaceTester.java
Since 0.4.1 there are two calls to MongoWorkspaceDB.getObjects in each
Workspace.getObjects call - one for standard objects and one for object
reference paths. Each MWDB.GO call checked data limits independently,
which meant that twice the allowed data limit could be stored on disk,
in memory, and returned. 
Altered the MWDB.getObjects calls so that the set of two calls shares
the same limits.
Went down the temp files rabbit hole and reworked temp files management
in a number of places.
* Made all workspace level tests check for temp files.
* Fixed a bug where sort errors could leave temp files on disk.
* Made the server level tempfiles cleanup easier to understand and less
prone to failure.
* Fixed a bug where getObjects() errors could leave temp files on disk for similar
reasons to the …
=> Fix bug in getObjects wrt returned data size, temp files refactor

src/us/kbase/typedobj/core/SubdataExtractor.java, src/us/kbase/typedobj/core/SubsetSelection.java, src/us/kbase/typedobj/test/ObjectExtractionByPathTest.java, src/us/kbase/workspace/WorkspaceServer.java, src/us/kbase/workspace/database/ByteArrayFileCacheManager.java, src/us/kbase/workspace/database/ObjIDWithChainAndSubset.java, src/us/kbase/workspace/database/ObjIDWithRefPathAndSubset.java, src/us/kbase/workspace/database/ObjectIDWithRefPath.java, src/us/kbase/workspace/database/Workspace.java, src/us/kbase/workspace/database/WorkspaceDatabase.java, src/us/kbase/workspace/database/mongo/MongoWorkspaceDB.java, src/us/kbase/workspace/kbase/IdentifierUtils.java, src/us/kbase/workspace/test/database/mongo/MongoInternalsTest.java, src/us/kbase/workspace/test/kbase/IdentifierUtilsTest.java, src/us/kbase/workspace/test/workspace/WorkspaceLongTest.java, src/us/kbase/workspace/test/workspace/WorkspaceTest.java, src/us/kbase/workspace/test/workspace/WorkspaceTester.java
Renamed and cleaned up a number of classes to avoid confusion between the path through the workspace reference graph and the paths into an object for the purposes of subset selection.
Went through getObjects and getObjectInformation and refactored variable names in preparation for what's to come
=> Refactoring class names

src/us/kbase/workspace/database/Workspace.java, src/us/kbase/workspace/database/mongo/MongoWorkspaceDB.java, src/us/kbase/workspace/test/database/mongo/MongoInternalsTest.java, src/us/kbase/workspace/test/kbase/JSONRPCLayerTest.java, src/us/kbase/workspace/test/workspace/WorkspaceTest.java
Errors for missing objects now provide the workspace name and ID, vs just the ID.
=> Simplify getObjects error handling & improve error information

src/us/kbase/workspace/database/Workspace.java, src/us/kbase/workspace/database/refsearch/ReferenceDAGTopologyProvider.java, src/us/kbase/workspace/database/refsearch/ReferenceProviderException.java, src/us/kbase/workspace/database/refsearch/ReferenceSearchFailedException.java, src/us/kbase/workspace/database/refsearch/ReferenceSearchMaximumSizeExceededException.java, src/us/kbase/workspace/database/refsearch/SearchReferenceDAG.java, src/us/kbase/workspace/test/workspace/WorkspaceTest.java
Was going to get too messy if I tried to jam all the necessary tree classes into the same class.
=> Move reference searching code into package & extract internal classes.

docsource/releasenotes.rst, performance/us/kbase/workspace/performance/workspace/GetObjectsTiming.java, src/us/kbase/workspace/WorkspaceServer.java, src/us/kbase/workspace/database/Types.java, src/us/kbase/workspace/kbase/WorkspaceAdministration.java, src/us/kbase/workspace/test/kbase/JSONRPCLayerTest.java, src/us/kbase/workspace/test/kbase/JSONRPCLayerTester.java
Since allTypes was a list rather than a set, it wound up with two copies
of each type when the types in the new specfile were the same as the old
specfile. In the first time through the loop, the type was removed from
typesToSave, and in the second time added to typesToUnregister. Thus any
types that are in the new spec and the old spec will be unregistered.
Changing the list to a set fixed the bug - the tests now fail on a list,
but pass with a set.
=> Fix bug with register_typespec_copy & updated specs

src/us/kbase/workspace/database/Workspace.java, src/us/kbase/workspace/database/WorkspaceDatabase.java, src/us/kbase/workspace/database/WorkspaceInformation.java, src/us/kbase/workspace/database/mongo/MongoWorkspaceDB.java, src/us/kbase/workspace/database/mongo/QueryMethods.java, src/us/kbase/workspace/kbase/WorkspaceAdministration.java, src/us/kbase/workspace/test/database/mongo/MongoInternalsTest.java, src/us/kbase/workspace/test/workspace/WorkspaceTest.java, src/us/kbase/workspace/test/workspace/WorkspaceTester.java
Mostly code documentation, clarification, and fixing several bugs found while clarifying and documenting code.
Bugs
* No longer suppresses errors when modifying locked workspaces
* Fortunately only read methods were doing this currently
* Fixed a bug where deleted workspaces were being returned when inappropriate
* Again, fortunately deleted object checks later in the code meant this bug currently had no impact
* Fixed a bug in setWorkspaceOwner where illegal workspace names could be set based on pretty specific inputs.
Decoupled various getWorkspaceInfo calls from other method calls. The methods now return void and the getWorkspaceInfo calls are pulled up a layer. Also eliminated a getWorkspaceInfo call when cloning a workspace, as all the info to create the WorkspaceInfo object is …
=> TASK-806 Prep for adding admin version of get_workspace_info PTII

docsource/releasenotes.rst, src/us/kbase/workspace/database/ObjectResolver.java, src/us/kbase/workspace/database/PermissionsCheckerFactory.java, src/us/kbase/workspace/database/Workspace.java, src/us/kbase/workspace/database/WorkspaceDatabase.java, src/us/kbase/workspace/database/mongo/MongoWorkspaceDB.java, src/us/kbase/workspace/test/workspace/ObjectResolverTest.java, src/us/kbase/workspace/test/workspace/WorkspaceTest.java
If an object was set for search, was in a readable workspace, and was
deleted, the lookup would fail even if there was a valid reference path
to the object.
The refactor to fix this bug also led to simplification of the search
code.
=> TASK-831 Refactor objectresolver & fix bug

src/us/kbase/workspace/database/ObjectResolver.java, src/us/kbase/workspace/test/workspace/ObjectResolverTest.java
Allows resolving objects as an admin (e.g. assuming all workspaces are readable).
Deleted objects can only be accessed by reference path from a non-deleted object or a search that finds a non-deleted object as per the workspace design constraints.
Next is to add glue code to the Workspace and JSONRPC layers to handle the admin case.
=> TASK-831 Add admin functionality to ObjectResolver

.classpath, deploy.cfg.example, src/us/kbase/typedobj/core/TypedObjectValidator.java, src/us/kbase/workspace/database/ResourceUsageConfigurationBuilder.java, src/us/kbase/workspace/database/Workspace.java, src/us/kbase/workspace/database/WorkspaceInformation.java, src/us/kbase/workspace/kbase/InitWorkspaceServer.java, src/us/kbase/workspace/kbase/KBaseWorkspaceConfig.java, src/us/kbase/workspace/listener/BadListenerFactory.java, src/us/kbase/workspace/listener/ListenerInitializationException.java, src/us/kbase/workspace/listener/NullListenerFactory.java, src/us/kbase/workspace/listener/WorkspaceEventListener.java, src/us/kbase/workspace/listener/WorkspaceEventListenerFactory.java, src/us/kbase/workspace/listener/package-info.java, src/us/kbase/workspace/test/workspace/WorkspaceConstructorTest.java, src/us/kbase/workspace/test/workspace/WorkspaceListenerTest.java
Allows implementing and loading workspace event listeners at startup without touching workspace code.
Currently only listens to workspace create and clone events. 
TODO Add other events of interest.
=> TASK-833 Add event listener framework

build.xml, docsource/releasenotes.rst, src/us/kbase/workspace/database/GetObjectInformationParameters.java, src/us/kbase/workspace/database/mongo/MongoWorkspaceDB.java, src/us/kbase/workspace/database/mongo/ObjectInfoUtils.java, src/us/kbase/workspace/test/workspace/WorkspaceTest.java, test/sorting/LoadSortData.java, test/sorting/listObjectsSort.md, test/sorting/package-info.java
New indexes in versions collection:
savedby
ws asc, id asc, ver dec
Listing objects will now sort by ws asc, id asc, ver dec if no filters
other than the object ID filters are specified. This makes it simpler to
list all objects in a workspace since you know if you've got all the
versions of an object without having to make another query.
Timing data shows no difference in adding the sort.
Tested with mongo explain() to be sure an index was used for sorting.
=> Sort listObject output when possible, new indexes

Dockerfile, Makefile, deployment/bin/start_workspace.sh, deployment/conf/.templates/start_workspace.sh.templ, server_scripts/glassfish_administer_service.py
Also move default glassfish http listener port off 8080 so that workspace service can use that port if necessary (which we want in order to make container deployments consistent)
=> Make port, jvm memory size and threads configurable at container startup

.classpath, build.xml, src/us/kbase/common/test/TestCommon.java, src/us/kbase/workspace/test/database/mongo/ShockBlobStoreTest.java, src/us/kbase/workspace/test/kbase/HandleTest.java, src/us/kbase/workspace/test/kbase/JSONRPCLayerTester.java, src/us/kbase/workspace/test/kbase/LoggingTest.java, src/us/kbase/workspace/test/workspace/WorkspaceTester.java, test.cfg.example
Starts a local instance of the auth service when running tests rather than relying on test accounts in a remote auth service.
This (eventually) enables Travis testing and greatly eases testing future developments using the auth services as a roles manager for the workspace (e.g. admin / read only roles, etc).
=> Use local auth for tests

src/us/kbase/typedobj/core/Restreamable.java, src/us/kbase/typedobj/core/ValidatedTypedObject.java, src/us/kbase/workspace/database/mongo/BlobStore.java, src/us/kbase/workspace/database/mongo/GridFSBlobStore.java, src/us/kbase/workspace/database/mongo/MongoWorkspaceDB.java, src/us/kbase/workspace/database/mongo/ShockBlobStore.java, src/us/kbase/workspace/test/database/mongo/GridFSBlobStoreTest.java, src/us/kbase/workspace/test/database/mongo/ShockBlobStoreTest.java, test/performance/ConfigurationsAndThreads.java
The MIME corruption fix will require streaming the input to Shock
multiple times, so a regular InputStream input won't work.
=> SCT-636 MIME corruption fix pt1: Restreamable input

performance/us/kbase/workspace/performance/workspace/GetObjectsMongoWSDB.java, performance/us/kbase/workspace/performance/workspace/ShockBackendTiming.java, src/us/kbase/workspace/database/mongo/ShockBlobStore.java, src/us/kbase/workspace/kbase/InitWorkspaceServer.java, src/us/kbase/workspace/test/database/mongo/ShockBlobStoreTest.java, src/us/kbase/workspace/test/workspace/WorkspaceTester.java, test/performance/ConfigurationsAndThreads.java, test/performance/GetObjectsLibSpeedTest.java
Make the shock client injectable so that responses from Shock can be
mocked for cases where we don't know how to reproduce the behavior (e.g.
appending MIME headers to data)
=> SCT-636 MIME corruption fix pt2: Dependency injection for shock client

docsource/releasenotes.rst, src/us/kbase/workspace/database/DependencyStatus.java, src/us/kbase/workspace/database/mongo/ShockBlobStore.java, src/us/kbase/workspace/test/database/DependencyStatusTest.java, src/us/kbase/workspace/test/database/mongo/ShockBlobStoreIntegrationTest.java, src/us/kbase/workspace/test/database/mongo/ShockBlobStoreTest.java
More of a workaround than a fix - just checks that the MD5 is the same
between shock and the workspace, and if not, deletes the node and tries
again.
The actual changes to the logic are pretty small; most of the PR is adding unit tests. Only integration tests existed before, which couldn't reproduce the bug.
=> SCT-636 Fix for MIME header corruption in shock nodes

src/us/kbase/workspace/kbase/InitWorkspaceServer.java, src/us/kbase/workspace/kbase/admin/AdminRole.java, src/us/kbase/workspace/kbase/admin/AdministratorHandler.java, src/us/kbase/workspace/kbase/admin/AdministratorHandlerException.java, src/us/kbase/workspace/kbase/admin/DefaultAdminHandler.java, src/us/kbase/workspace/kbase/admin/WorkspaceAdministration.java, src/us/kbase/workspace/test/kbase/LoggingTest.java, src/us/kbase/workspace/test/kbase/admin/DefaultAdminHandlerTest.java
Allows different sources of administrators. Currently only workspace
internal admin list is supported.
Also allows for read only admin role.
Next step is implementing the interface for auth2 roles.
=> Add AdministratorHandler interface

docsource/events.rst, src/us/kbase/workspace/database/Util.java, src/us/kbase/workspace/kbase/admin/KBaseAuth2AdminHandler.java, src/us/kbase/workspace/test/kbase/JSONRPCLayerTest.java, src/us/kbase/workspace/test/kbase/KBaseAuth2AdminHandlerTest.java
Eventually will allow specifying WS admins in the auth service.
TODO:
* Add read only mode in administrator class & unit test
* Add token cache in administrator class
* Add roles to config and add auth service handler to service build
* Add integration tests
* Documentation
=> Add an administrator handler for the KBase auth service

src/us/kbase/typedobj/db/MongoTypeStorage.java
Adds an object mapper to replace the mapper in Jongo. Unlike the WS DB
provenance object, the objects in the TDB look simple enough that this
approach should work in a lot, if not all, cases.
Since the load on the TBD is very low and the TD objects are small, not
worried about any overhead from remapping the objects.
=> SCT-1770 remove jongo overlay from several type DB methods

src/us/kbase/common/test/TestCommon.java, src/us/kbase/workspace/kbase/admin/WorkspaceAdministration.java, src/us/kbase/workspace/test/kbase/JSONRPCLayerTest.java, src/us/kbase/workspace/test/kbase/JSONRPCLayerTester.java, src/us/kbase/workspace/test/kbase/admin/KBaseAuth2AdminHandlerTest.java, src/us/kbase/workspace/test/kbase/admin/WorkspaceAdministrationTest.java
Still need to test everything after create workspace, but this is
getting pretty big.
next batch of tests will cover the rest.
TODO:
add to build - need 2 new config items
add token cache in admin class (not in handler classes)
integration tests
docs
=> Add read only check to workspace administrator class

src/us/kbase/workspace/kbase/InitWorkspaceServer.java, src/us/kbase/workspace/kbase/admin/KBaseAuth2AdminHandler.java, src/us/kbase/workspace/kbase/admin/WorkspaceAdministration.java, src/us/kbase/workspace/test/kbase/admin/WorkspaceAdministrationTest.java
Since the workpace administration call is used by search and other
services to retrieve data, we cache the administration role of a user
for 5 minutes to reduce load on the admin role source (basically the
auth server) and speed up the calls. No point in fetching the user data
over and over every millisecond.
The token is already cached by the auth client, but the user info is not.
TODO
add to build - need 2 new config items
integration tests
docs
=> SCT-223 Add cache for admin role to workspace administration method

src/us/kbase/workspace/WorkspaceServer.java, src/us/kbase/workspace/database/Provenance.java, src/us/kbase/workspace/database/mongo/MongoWorkspaceDB.java, src/us/kbase/workspace/test/database/mongo/MongoWorkspaceDBTest.java, src/us/kbase/workspace/test/kbase/JSONRPCLayerTest.java
Previously, Jongo just set the field directly rather than using the
method call.
=> Fix NPE when getting objects saved before v0.4.1

src/us/kbase/workspace/database/WorkspaceObjectData.java, src/us/kbase/workspace/database/mongo/MongoWorkspaceDB.java, src/us/kbase/workspace/kbase/ArgUtils.java, src/us/kbase/workspace/kbase/WorkspaceServerMethods.java, src/us/kbase/workspace/test/workspace/WorkspaceTest.java, src/us/kbase/workspace/test/workspace/WorkspaceTester.java
Wrap the ID reference type in its proper class
This will be useful for a) the update to the new handle manager and b)
adding new ID types (like links directly to shock or the new data
stsore)
=> Prep for modularizing ID reference permission updates

src/us/kbase/typedobj/idref/IdReferenceHandlerSet.java, src/us/kbase/typedobj/idref/IdReferenceHandlerSetFactory.java, src/us/kbase/typedobj/idref/IdReferenceHandlerSetFactoryBuilder.java, src/us/kbase/typedobj/idref/IdReferencePermissionHandlerSet.java, src/us/kbase/typedobj/idref/NoSuchIdReferenceHandlerException.java, src/us/kbase/typedobj/test/DummyIdHandlerFactory.java, src/us/kbase/typedobj/test/idref/IdReferenceHandlerSetFactoryBuilderTest.java, src/us/kbase/typedobj/test/idref/IdReferencePermissionHandlerSetTest.java, src/us/kbase/workspace/WorkspaceServer.java, src/us/kbase/workspace/database/Workspace.java, src/us/kbase/workspace/kbase/ArgUtils.java, src/us/kbase/workspace/kbase/HandleIdHandlerFactory.java, src/us/kbase/workspace/kbase/InitWorkspaceServer.java, src/us/kbase/workspace/kbase/WorkspaceServerMethods.java, src/us/kbase/workspace/test/kbase/HandleIdHandlerFactoryTest.java, src/us/kbase/workspace/test/kbase/HandleTest.java, src/us/kbase/workspace/test/workspace/TestIDReferenceHandlerFactory.java
Currently only affect handles. The code that set permissions on handles
was buried fairly deep in the code and was not extensible to other ID
types. Add a permissions abstraction so that 1) it is extensible and 2)
the handle code is isolated to a single class, not spread all over.
=> Refactor the id handling on fetch object

src/us/kbase/workspace/kbase/ShockIdHandlerFactory.java, src/us/kbase/workspace/test/kbase/HandleAndShockTest.java, src/us/kbase/workspace/test/kbase/ShockIdHandlerFactoryTest.java
A crafty user could create a Shock node and then chown it to the
workspace user account that handles linking Shock nodes, which would
allow them to retain their delete and write perms, which is bad.
Now when the handler encounters a node is already owns (and therefore
doesn't need to copy) it wipes out the delete and write ACLS.
=> Fix shock ID handler bug

.classpath, build.xml, src/us/kbase/workspace/database/mongo/BlobStore.java, src/us/kbase/workspace/database/mongo/GridFSBlobStore.java, src/us/kbase/workspace/database/mongo/S3BlobStore.java, src/us/kbase/workspace/database/mongo/ShockBlobStore.java, src/us/kbase/workspace/test/database/mongo/GridFSBlobStoreTest.java, src/us/kbase/workspace/test/database/mongo/ShockBlobStoreIntegrationTest.java, test/s3presignedurl/S3PresignedURLExample.java
Also removed BlobStore.getExternalIdentifier(). Unused and leaks implementation details.
test/s3presignedurl/S3PresignedURLExample.java isn't actually used anywhere, but it's useful code to test error handling so I'm checking it in.
=> S3 SDK V2 presigned url workaround example

.travis.yml, build.xml, src/us/kbase/workspace/database/exceptions/ErrorOr.java, src/us/kbase/workspace/database/exceptions/ErrorType.java, src/us/kbase/workspace/database/mongo/MongoWorkspaceDB.java, src/us/kbase/workspace/test/workspace/ErrorOrTest.java
This class will be used to return either an object, such as a Workspace
object, or an error code that explains why the object could not be
retrieved. The error code will be exposed in API methods that use the
ignoreError parameter rather than just a null value.
=> Add ErrorOr class

src/us/kbase/workspace/kbase/HandleIdHandlerFactory.java, src/us/kbase/workspace/kbase/InitWorkspaceServer.java, src/us/kbase/workspace/test/kbase/HandleAndShockTest.java, src/us/kbase/workspace/test/kbase/HandleIdHandlerFactoryTest.java
Looks like cruft leftover from prior to the handle service / handle
manager merge
This class will be used as the starting point for the Sample service
integration, so cleanliness is important
=> Clean up Handle ID handler factory initialization

docsource/test.rst
build/config/install needs a rework badly (still references the
dev_container) but that's a lot more work and probably needs some helper
scripts / better instructions rather than just a 5m rewrite. Maybe just
provide a docker-compose.
=> Correct test instructions

.classpath, build.xml, src/us/kbase/typedobj/idref/IdReferencePermissionHandlerSet.java, src/us/kbase/workspace/kbase/SampleServiceClientWrapper.java, src/us/kbase/workspace/test/kbase/SampleServiceClientWrapperTest.java
The inability to initialize a client as either dynamic or standard means I need to roll my own, unfortunately.
This is a little on the large side but it's all greenfield, completely standalone, and 75% test code and so hopefully shouldn't be too difficult to understand.
=> Add sample service client

src/us/kbase/workspace/kbase/InitWorkspaceServer.java, src/us/kbase/workspace/test/controllers/handle/HandleServiceController.java, test.cfg.example
Code being removed provides the ability to automatically download the
handle service code from github and use it in the tests. But:
1) It's not used anywhere
2) It pull the latest version of the handle service files rather than a
pinned version
3) More code to maintain
Hence the removal
Also some minor text cleanup
=> Remove auto download option for handle service controller

src/us/kbase/common/test/TestCommon.java, test.cfg.example
Updates the test config example file for sample service configuration items and the test configuration helper code to pull said items.
=> Add arango and sample service to test configuration

src/us/kbase/workspace/test/controllers/sample/SampleServiceController.java, src/us/kbase/workspace/test/kbase/JSONRPCLayerTest.java
The workspace has to start up before the sample service, but it needs to
know the sample service URL, so the port has to be determined before the
sample service controller starts.
Also includes some minor test cleanup.
=> Allow assigning a port to the sample service

.travis.yml, python_dependencies/Pipfile, python_dependencies/Pipfile.lock, src/us/kbase/workspace/WorkspaceServer.java, src/us/kbase/workspace/kbase/InitWorkspaceServer.java, src/us/kbase/workspace/test/controllers/minio/MinioController.java, src/us/kbase/workspace/test/database/mongo/S3BlobStoreIntegrationTest.java, src/us/kbase/workspace/test/kbase/JSONRPCLayerTest.java, src/us/kbase/workspace/test/kbase/JSONRPCLayerTester.java, src/us/kbase/workspace/test/kbase/SampleServiceIntegrationTest.java
Next PRs will fill out the tests. However, all the code changes that can be covered without bringing up dependent servers in  various states of usability are currently covered. Uncovered code is tested manually as it is not expected to change often.
Notes:
* focal caused the minio-related tests to fail. Not clear why this is.
* trying to install and use a python version that doesn't pre-exist in travis is a nightmare.
* trusty doesn't include python3.7 but xenial does. Bionic may work as well. Focal does not for the reason above.
* uwsgi 2.0.19 seemed to have build problems, so pinned to 2.0.18.
* Python's SSL module is broken on Trusty: deadsnakes/issues#63 . This prevented get-pip.py from working.
Everything that was tried to get Travis to finally work is preserved here: …
=> Add sample service test rig and one simple test

.classpath, build.xml, src/us/kbase/workspace/database/mongo/S3ClientWithPresign.java
Notes:
The behavior of the expiration time changed with the new clients and
caused all S3 saves to fail, so for now I removed the expiration time.
This means the expiration time will default to a week:
https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/auth/signer/params/Aws4PresignerParams.Builder.html#expirationTime-java.time.Instant-
Since the URL with the creds only lives in the workspace memory and the
reference is released as soon as the object is saved, this doesn't seem
like a huge problem, as the intent is to replace the presign code next.
This PR is branching off of dev-candidate slightly after the last merge
to develop to pick up the Jackson jars updates. However, it's branched
*prior* to any sample service changes so this can be merged without
bringing in all …
=> Update the S3 jars.

src/us/kbase/workspace/database/mongo/S3ClientWithPresign.java
The updated S3 client now has built in presign functionality, use that
instead of the prior workaround
Also restore the 15m expiration time for signed URLs
=> Replace S3 presign implementation

src/us/kbase/typedobj/idref/IdReferenceHandlerSetFactory.java, src/us/kbase/typedobj/test/DummyIdHandlerFactory.java, src/us/kbase/workspace/database/Workspace.java, src/us/kbase/workspace/kbase/HandleIdHandlerFactory.java, src/us/kbase/workspace/kbase/SampleIdHandlerFactory.java, src/us/kbase/workspace/kbase/ShockIdHandlerFactory.java, src/us/kbase/workspace/test/kbase/HandleIdHandlerFactoryTest.java, src/us/kbase/workspace/test/kbase/SampleIDHandlerFactoryTest.java, src/us/kbase/workspace/test/kbase/SampleServiceIntegrationTest.java, src/us/kbase/workspace/test/kbase/ShockIdHandlerFactoryTest.java, src/us/kbase/workspace/test/workspace/TestIDReferenceHandlerFactory.java
Makes much more sense and will allow simplifying the WorkspaceServer and
the InitWorkspace classes. Will also make it easier to add more ID types
in future as changes to those classes will no longer be necessary.
Next: integrate into the rest of the server and remove dependency checking code from the WorkspaceServer class.
=> Add dependency checking code to the ID handlers

src/us/kbase/typedobj/idref/IdReferenceHandlerSetFactoryBuilder.java, src/us/kbase/typedobj/test/idref/IdReferenceHandlerSetFactoryBuilderTest.java, src/us/kbase/workspace/WorkspaceServer.java, src/us/kbase/workspace/kbase/WorkspaceServerMethods.java, src/us/kbase/workspace/test/kbase/HandleAndShockTest.java
Builds on the work from the past few commits.
Tests for `WorkspaceServerMethods` at this point are all integration tests that start at the JSON RPC API. Fixing that is waaaay out of scope for this PR. Nonetheless, the changes are tested.
Next step: Delete all the old dependency status code which is now cruft.
=> Get dependency status from the ID handlers vs. custom methods

src/us/kbase/workspace/kbase/SampleIdHandlerFactory.java, src/us/kbase/workspace/test/WorkspaceTestCommon.java, src/us/kbase/workspace/test/kbase/SampleIDHandlerFactoryTest.java
String interning caused `==` to work when the correct equality method is
using `equals()`
=> Fix bug in sample ID handler

.classpath, build.xml, docsource/releasenotes.rst, performance/us/kbase/workspace/performance/shockclient/SaveAndGetFromShock.java, src/us/kbase/common/test/service/ServiceCheckerTest.java, src/us/kbase/workspace/database/mongo/ShockBlobStore.java, src/us/kbase/workspace/test/database/mongo/ShockBlobStoreIntegrationTest.java, src/us/kbase/workspace/test/database/mongo/ShockBlobStoreTest.java, src/us/kbase/workspace/test/docserver/DocServerTest.java, src/us/kbase/workspace/test/kbase/HandleAndShockTest.java, test/performance/ConfigurationsAndThreads.java
As near as I can tell, how this screwup happened is:
* while developing the blobstore, I came up with a list of repos that required a shock client update.
* I left the workspace off that list since it would no longer talk to shock, but talk to S3 directly.
* Later, I added support for the `@bytestream` annotation that causes the workspace to talk to shock, but reasoned the client didn't need an update because the `@bytestream` code doesn't use any of the changed APIs.
* I forgot that on client startup the client *does* use one of the changed APIs invisibly to check the shock connection and credentials are fine.
* Apparently I never tested the bytestream stuff against the blobstore.
Lesson learned: always test everything against everything.
=> Update Shock client to 0.1.0 for blobstore compatibility

src/us/kbase/workspace/test/kbase/HandleAndShockTest.java
Frequently start up the services via the test with a debug pause and
then do manual testing. Having a simple spec makes this easier.
=> Add a trivial spec to make ad hoc testing easier

docsource/developers.rst
Becomes a merge / deploy nightmare with features competing to be the
next one out. Better to have separate feature branches.
=> Get rid of dev-candidate

docsource/shockintegration.rst, src/us/kbase/workspace/test/kbase/SampleServiceIntegrationTest.java
Apparently forgot to remove the TODO when the integration tests were
finished
=> Remove an old TODO and fix a typo

src/us/kbase/common/test/TestCommon.java, src/us/kbase/workspace/test/database/mongo/MongoWorkspaceDBTest.java
While looking into what it would take to add events for hide object state changes, I discovered that the return values for deleteObject state changes were completely untested. This adds unit (ish, MongoDB is running) tests for deleteObject. It also DRYs up object creation in tests, which is fairly complex this low in the workspace stack.
=> Add deleteObject unit tests

src/us/kbase/workspace/database/GetObjectInformationParameters.java, src/us/kbase/workspace/database/ListObjectsParameters.java, src/us/kbase/workspace/database/mongo/MongoWorkspaceDB.java, src/us/kbase/workspace/database/mongo/ObjectInfoUtils.java
A little cleanup before adding new features. No behavioral changes.
Major changes are:
* use try-with-resources to ensure `DBCursor` is always closed
* Move `isObjectIDFiltersOnly` from the parameters value class to the object lister
class. Really doesn't make sense where it is, and makes it harder to alter later if it's generally accessible.
* Inline a few functions that can be simplified to one line with `.stream()`
=> Object list fn code cleanup

src/us/kbase/typedobj/db/MongoTypeStorage.java, src/us/kbase/workspace/database/GetObjectInformationParameters.java, src/us/kbase/workspace/database/Workspace.java, src/us/kbase/workspace/database/mongo/MongoWorkspaceDB.java, src/us/kbase/workspace/database/mongo/ObjectLister.java, src/us/kbase/workspace/database/mongo/QueryMethods.java
For some reason getting the list of workspaces to which a user had
access allows specifying multiple users, which confused the hell out of
me. Turns out this feature and a couple of helper methods are unused, so
in the garbage they go.
Also some other minor cruft cleanup and force cursors to close.
=> Remove unused cruft, force cursor close

src/us/kbase/workspace/test/workspace/WorkspaceTester.java
Was only needed for Shock, which is no longer a supported backend.
Another discovery I made while figuring out how to set up a new integration test class, which I haven't done for the workspace in years
=> Remove auth server from WorkspaceTester test rig

performance/us/kbase/workspace/performance/refsearch/GetReferencedObjectWithBFS.java, performance/us/kbase/workspace/performance/workspace/GetObjectsMongoWSDB.java, src/us/kbase/workspace/database/Workspace.java, src/us/kbase/workspace/database/WorkspaceDatabase.java, src/us/kbase/workspace/database/mongo/MongoWorkspaceDB.java, src/us/kbase/workspace/kbase/InitWorkspaceServer.java, src/us/kbase/workspace/test/database/mongo/MongoInternalsTest.java, src/us/kbase/workspace/test/database/mongo/MongoStartUpTest.java, src/us/kbase/workspace/test/database/mongo/PartialMock.java, src/us/kbase/workspace/test/workspace/WorkspaceConstructorTest.java, src/us/kbase/workspace/test/workspace/WorkspaceIntegrationWithGridFSTest.java, src/us/kbase/workspace/test/workspace/WorkspaceListenerTest.java, src/us/kbase/workspace/test/workspace/WorkspaceTester.java, src/us/kbase/workspace/test/workspace/WorkspaceUnitTest.java, test/performance/GetObjectsLibSpeedTest.java
This was too stupid not to fix. Maybe `MongoWorkspaceDB` at some point
used `TempFilesManager` but now it doesn't touch TFM. Make the
`Workspace` class responsible for it since WS actually uses it.
=> Move WS DB dependency to class where it's actually used

.travis.yml, docsource/conf.py
Build is failing due to `gunicorn` and `uwsgi` not being in the path.
The last build that succeeded was on `pipenv-2021.5.29`, failed builds
were on `pipenv-2021.11.5.post0`. See https://github.com/pypa/pipenv/issues/4831
Going to the `dev-gavin-incoming` branch so a build will succeed when merging to develop
=> Fix build & update copyright

src/us/kbase/workspace/database/ObjectIdentifier.java, src/us/kbase/workspace/database/ObjectResolver.java, src/us/kbase/workspace/database/Workspace.java, src/us/kbase/workspace/test/kbase/IdentifierUtilsTest.java, src/us/kbase/workspace/test/workspace/WorkspaceTest.java
No need to do bizarre instanceof checking, can now hide the subclass
implementations
Future PRs:
* Write a builder to replace the 9 constructors and 2 create methods
that picks the right class to return
* Hide the 2 subclasses and refactor code that uses them
* Write unit tests for the ObjectIdentifier class
=> Add all ObjectIdentifier subclass methods to superclass

src/us/kbase/workspace/database/ObjectIdentifier.java, src/us/kbase/workspace/test/workspace/ObjectIdentifierTest.java
Quickly became clear that doing otherwise was going to result in a *lot*
of refactoring that probably wasn't worth it
Handy anyway
=> DATAUP-725: Add object identifier builder starting from OI

performance/us/kbase/workspace/performance/refsearch/GetReferencedObjectWithBFS.java, performance/us/kbase/workspace/performance/refsearch/v0_3_5/GetReferencedObjectWithBFS.java, src/us/kbase/common/test/TestCommon.java, src/us/kbase/workspace/WorkspaceServer.java, src/us/kbase/workspace/database/ObjectIdentifier.java, src/us/kbase/workspace/database/Workspace.java, src/us/kbase/workspace/kbase/IdentifierUtils.java, src/us/kbase/workspace/test/database/mongo/MongoInternalsTest.java, src/us/kbase/workspace/test/kbase/IdentifierUtilsTest.java, src/us/kbase/workspace/test/workspace/ObjectIDNoWSNoVerTest.java, src/us/kbase/workspace/test/workspace/ObjectResolverTest.java, src/us/kbase/workspace/test/workspace/PermissionsCheckerFactoryTest.java, src/us/kbase/workspace/test/workspace/WorkspaceIntegrationWithGridFSTest.java, src/us/kbase/workspace/test/workspace/WorkspaceListenerTest.java, src/us/kbase/workspace/test/workspace/WorkspaceLongTest.java, src/us/kbase/workspace/test/workspace/WorkspaceTest.java, src/us/kbase/workspace/test/workspace/WorkspaceTester.java, test/performance/GetObjectsLibSpeedTest.java
Delete the 11 (count 'em) different methods for creating an
`ObjectIdentifer` and use the fluent builder interface everywhere.
Real code changes aren't too crazy but the test changes are pretty
bonkers.
Still to do:
* Add unit tests for the rest of the class (maybe? having second thoughts about this given how long this has already taken, and the class has [good coverage](https://app.codecov.io/gh/kbase/workspace_deluxe/blob/develop/src/us/kbase/workspace/database/ObjectIdentifier.java) other than `toString` methods)
* Handle any remaining NOW TODOs in the class
=> DATAUP-725: Switch 11 ObjectIdentifier creation methods for 1 fluent builder

src/us/kbase/workspace/database/ObjectIdentifier.java, src/us/kbase/workspace/test/kbase/IdentifierUtilsTest.java, src/us/kbase/workspace/test/workspace/WorkspaceTest.java
Now an easy change to make. Assuming a HotSpot JVM with < 32GB of
heap, should reduce 48B to 12B for storing the numbers
Also some minor cleanup.
=> DATAUP-725: Switch to primitives in ObjectIdentifier instance vars

src/us/kbase/workspace/database/ObjectIdentifier.java, src/us/kbase/workspace/database/Reference.java, src/us/kbase/workspace/database/Workspace.java, src/us/kbase/workspace/database/mongo/ObjectIDResolvedWSNoVer.java, src/us/kbase/workspace/kbase/IdentifierUtils.java, src/us/kbase/workspace/test/kbase/IdentifierUtilsTest.java, src/us/kbase/workspace/test/workspace/ObjectIdentifierTest.java, src/us/kbase/workspace/test/workspace/WorkspaceLongTest.java, src/us/kbase/workspace/test/workspace/WorkspaceTest.java, src/us/kbase/workspace/test/workspace/WorkspaceTester.java
... so all builds work the same way. Missed this one originally.
Also move all the ref tests into the OI unit tests where they should be.
=> DATAUP-725: Make a builder for creating an ObjectInformation from a ref

performance/README.md, performance/us/kbase/workspace/performance/workspace/GetObjectsMongoWSDB.java, src/us/kbase/workspace/database/Workspace.java, src/us/kbase/workspace/database/WorkspaceDatabase.java, src/us/kbase/workspace/database/WorkspaceObjectData.java, src/us/kbase/workspace/database/mongo/MongoWorkspaceDB.java, src/us/kbase/workspace/test/database/mongo/MongoWorkspaceDBTest.java, src/us/kbase/workspace/test/workspace/WorkspaceObjectDataTest.java
Sets the stage for separating getting the object info / provenance /
etc. and then adding the data later, after the max data size has been
calculated. Since the max size is calculated up front, before getting the data,
we can ditch the non-thread safe data size management code.
=> DATAUP-725: Return object data builder from DB layer & use

src/us/kbase/workspace/database/Util.java, src/us/kbase/workspace/database/WorkspaceObjectData.java, src/us/kbase/workspace/test/workspace/WorkspaceObjectDataTest.java
* Subset data will be necessary for the rewritten object data pulling code that will take `WorkspaceObjectData.Builder`s as input, since that method will do the subsetting
* Getting the object information from the builder is necessary to get access to the object size in bytes, which will be used to calculate the total size of the requested data and, based on that size, either
* store it in memory
* store it on disk
* throw an error because it's too big
The WOD won't be built until after the data is added, so the size needs to be available from the builder API.
=> DATAUP-725: Add subset data and getter for ObjectInformation to WOD builder

src/us/kbase/workspace/database/ByteArrayFileCacheManager.java, src/us/kbase/workspace/database/ObjectInformation.java, src/us/kbase/workspace/database/WorkspaceDatabase.java, src/us/kbase/workspace/database/exceptions/NoObjectDataException.java, src/us/kbase/workspace/database/mongo/MongoWorkspaceDB.java, src/us/kbase/workspace/test/database/mongo/MongoWorkspaceDBTest.java
Next step is to return no data from the MWDB.getObjects method and
use this method to populate the builder with data. Then the data size
calculation can be done in the Workspace class and the
ByteArrayFileCacheManager can be initialized up front to save to memory
or disk, getting rid of the thread unsafe dynamic reallocation code.
=> DATAUP-725: Add method to add data to WorkspaceObjectData builder

performance/us/kbase/workspace/performance/workspace/GetObjectsMongoWSDB.java, src/us/kbase/common/test/TestCommon.java, src/us/kbase/workspace/database/Workspace.java, src/us/kbase/workspace/database/WorkspaceDatabase.java, src/us/kbase/workspace/database/mongo/MongoWorkspaceDB.java, src/us/kbase/workspace/test/database/mongo/MongoInternalsTest.java, src/us/kbase/workspace/test/database/mongo/MongoWorkspaceDBTest.java, src/us/kbase/workspace/test/workspace/WorkspaceTest.java, src/us/kbase/workspace/test/workspace/WorkspaceUnitTest.java
Next: rewrite the BAFCM constructor to just take a boolean that tells it
to store data on disk or in memory, and get rid of the thread unsafe
size calculations.
Seems like the code is quite a bit simpler overall by splitting
MWSDB.getOBjects() into two methods
=> DATAUP-725: Use the new data addition method in WS.getObjects()

src/us/kbase/typedobj/core/TypedObjectValidator.java, src/us/kbase/workspace/database/ObjectIdentifier.java, src/us/kbase/workspace/database/Workspace.java, src/us/kbase/workspace/database/provenance/Common.java, src/us/kbase/workspace/kbase/IdentifierUtils.java, src/us/kbase/workspace/kbase/WorkspaceServerMethods.java, src/us/kbase/workspace/test/kbase/IdentifierUtilsTest.java, src/us/kbase/workspace/test/kbase/JSONRPCLayerTest.java, src/us/kbase/workspace/test/workspace/ObjectIdentifierTest.java, src/us/kbase/workspace/test/workspace/ReferenceTest.java, src/us/kbase/workspace/test/workspace/WorkspaceTest.java
Turns out I'll need a reference path validator for the provenance work.
The first step is to make a single parser rather than having it split
into two chunks. Improves code cohesion as well.
\* mostly, there's still some stuff in IdentifierUtils but it does weird
things around rearranging the ref order that I don't want to touch for
now
=> PTV-1733: Consolidate* reference parsing code

src/us/kbase/workspace/kbase/InitWorkspaceServer.java
Slightly hacky but fine in the startup code
=> Print a stacktrace when the server can't start

deploy.cfg.example, deployment/conf/.templates/deployment.cfg.templ, docsource/buildandconfigure.rst, docsource/releasenotes.rst, src/us/kbase/workspace/kbase/InitWorkspaceServer.java, src/us/kbase/workspace/kbase/KBaseWorkspaceConfig.java, src/us/kbase/workspace/test/kbase/KBaseWorkspaceConfigTest.java
The update of the MongoDB driver from v3.8 to v3.12 has a change where
the retryWrites parameter default is now true. This causes the workspace
service to fail to start in KBase CI. Locally and in Travis CI
everything is fine, so to truly test the fix we'll need to start the
service in KBase CI.
=> Add the MongoDB retryWrites param to the config

src/us/kbase/workspace/kbase/InitWorkspaceServer.java, src/us/kbase/workspace/kbase/admin/AdministrationCommandSetBuilder.java, src/us/kbase/workspace/kbase/admin/WorkspaceAdministration.java, src/us/kbase/workspace/test/kbase/admin/WorkspaceAdministrationWithHandlersTest.java
Makes it easier to run with different sets of admin commands or different implementations of the same set
Step two of this process is making a WorkspaceAdministrator builder and using that instead of just taking a map of admin commands in the constructor. At that point I'll also add new WA unit tests.
=> PTV-1786: Separate the admin commands from the admin framework

src/us/kbase/typedobj/core/LocalTypeProvider.java, src/us/kbase/typedobj/core/TypeProvider.java, src/us/kbase/typedobj/core/TypedObjectValidator.java, src/us/kbase/typedobj/test/LocalTypeProviderTest.java, src/us/kbase/typedobj/test/TypeProviderTest.java
The absolute type def and the jsonschema can be fetched in one call to
the workspace, so make the provider a single call.
=> PTV-1786: Simplify type provider interface

.classpath, build.xml, src/us/kbase/typedobj/core/TypeDefName.java, src/us/kbase/workspace/kbase/DelegatingTypeProvider.java, src/us/kbase/workspace/test/kbase/DelegatingTypeProviderTest.java, src/us/kbase/workspace/version/WorkspaceVersion.java
for the type validator.
There's a bug in the caching strategy wherein providing an absolute type id could return a newer type than providing a non-absolute type id for the same type, which shouldn't happen. The next PR will fix that bug as this PR is really large already and it'll require more code and more tests.
=> PTV-1786: Add Delegating Type Provider

src/us/kbase/workspace/kbase/DelegatingTypeServerMethods.java, src/us/kbase/workspace/kbase/TypeClient.java, src/us/kbase/workspace/kbase/TypeDelegationException.java, src/us/kbase/workspace/kbase/TypeServerMethods.java, src/us/kbase/workspace/kbase/WorkspaceDelegator.java, src/us/kbase/workspace/kbase/admin/AdministrationCommandSetInstaller.java, src/us/kbase/workspace/test/kbase/TypeClientTest.java, src/us/kbase/workspace/test/kbase/WorkspaceDelegatorTest.java, src/us/kbase/workspace/test/workspace/WorkspaceUnitTest.java
Effectively combines DelegatingTypeServerMethods and WorkspaceDelegator into one class. This has 2 benefits:
1) It makes it much simpler to switch to a TypeServiceClient when that exists since you only have to worry about changing one class
2) It makes the tests much simpler since all the delegation functional interface stuff is hidden
Next step is replacing the 2 classes with the new class.
=> PTV-1786: Simplify type operation delegation part 1/2

src/us/kbase/common/test/TestCommon.java, src/us/kbase/workspace/database/Util.java, src/us/kbase/workspace/database/provenance/Common.java, src/us/kbase/workspace/database/provenance/Organization.java, src/us/kbase/workspace/test/database/UtilTest.java, src/us/kbase/workspace/test/database/provenance/OrganizationTest.java, src/us/kbase/workspace/test/database/provenance/ProvenanceTestCommon.java
this should slot in before the [CE-94 / PID pull request](https://github.com/kbase/workspace_deluxe/pull/636).
- moved the various test constants out of TestCommon and into WorkspaceTestCommon
- implemented the PID checker and added the ability to return null if the dbxref is null or empty
- minor refactoring of the Organization tests to be better organised
=> CE-93: implement PIDs; use shared constants

src/us/kbase/workspace/database/provenance/Common.java, src/us/kbase/workspace/database/provenance/PermanentID.java, src/us/kbase/workspace/test/database/UtilTest.java, src/us/kbase/workspace/test/database/provenance/OrganizationTest.java, src/us/kbase/workspace/test/database/provenance/PermanentIDTest.java
PermanentID class:
id: mandatory, must match regex
description: optional, free text
relationshipType: optional, currently free text but may be restricted to a controlled vocab in the future
=> CE-94 revisited: Adding PID class with tests

src/us/kbase/workspace/database/provenance/Common.java, src/us/kbase/workspace/database/provenance/Event.java, src/us/kbase/workspace/database/provenance/EventDate.java, src/us/kbase/workspace/test/database/provenance/EventDateTest.java, src/us/kbase/workspace/test/database/provenance/EventTest.java
New event date class, all fields mandatory.
`date`: will be parsed by the credit engine and then formatted as YYYY, YYYY-MM, or YYYY-MM-DD, depending on the level of specificity of the input
`dateFormat`: string literal representing the date; will be `YYYY`, `YYYY-MM`, or `YYYY-MM-YY`
`event`: string describing what the event was -- e.g. dataset created, dataset published, dataset embargo lifted, etc.
=> CE-95: event date

workspace.spec
Couple of minor spec changes:
- comments field is now a list of strings
- more text about the default resource_type, 'dataset'
- clarify license / license URL info
- rename CreditMetadataContainer -> CreditMetadataEntry to sound a bit more colloquial and less computer-y.
=> CE-151: update to CreditMetadata schema

src/us/kbase/workspace/database/provenance/FundingReference.java, src/us/kbase/workspace/test/database/provenance/CreditMetadataTest.java, src/us/kbase/workspace/test/database/provenance/FundingReferenceTest.java
Some schema changes brought about after aligning the schema with schema.org:
- use an organisation object instead of having funder_name and funder_id
- switch from using 'award' to using 'grant' instead
I'll need to update the spec and the generated classes but have a few other schema alterations to make, so will do them first.
=> CE-225: Award => grant, org name/ID to Organization object

src/us/kbase/workspace/database/provenance/CreditMetadata.java, src/us/kbase/workspace/test/database/provenance/CreditMetadataEntryTest.java, src/us/kbase/workspace/test/database/provenance/CreditMetadataTest.java
Adding a description and repository field to the credit metadata
=> CE-225: new credit metadata fields

src/us/kbase/workspace/database/mongo/MongoWorkspaceDB.java, src/us/kbase/workspace/test/database/mongo/MongoInternalsTest.java, src/us/kbase/workspace/test/database/mongo/MongoWorkspaceDBTest.java
... in preparation for setting object admin metadata which will hopefully reuse the code
=> Simplify setting workspace metadata & add tests

src/us/kbase/workspace/database/Workspace.java, src/us/kbase/workspace/database/WorkspaceDatabase.java, src/us/kbase/workspace/database/mongo/MongoWorkspaceDB.java, src/us/kbase/workspace/test/database/mongo/MongoWorkspaceDBTest.java, src/us/kbase/workspace/test/workspace/WorkspaceListenerTest.java
... so there isn't a db call for EVERY SINGLE REMOVE KEY WTF WAS THAT IDIOT THINKING oh wait that was me
=> Integrate the 2 ws meta alteration methods & make all changes in 1 shot

src/us/kbase/workspace/database/ObjectIDResolvedWS.java, src/us/kbase/workspace/database/WorkspaceDatabase.java, src/us/kbase/workspace/database/mongo/Fields.java, src/us/kbase/workspace/database/mongo/MongoWorkspaceDB.java, src/us/kbase/workspace/database/mongo/ObjectInfoUtils.java, src/us/kbase/workspace/database/mongo/ObjectLister.java, src/us/kbase/workspace/test/database/mongo/MongoWorkspaceDBTest.java, src/us/kbase/workspace/test/database/mongo/ObjectListerTest.java, src/us/kbase/workspace/test/database/mongo/PartialMock.java, src/us/kbase/workspace/test/workspace/WorkspaceTest.java, src/us/kbase/workspace/test/workspace/WorkspaceTester.java
... and alter all the methods that touch object information to copy or return it correctly.
Ideally we would've:
* Made some type of field manager so mongo field lists aren't respecified all over the place
* Added less integration-y tests for the altered methods in MongoWorkspaceDBTest, rather than jamming tests into WorkspaceTest
However, that would have added several days to this project which we don't have.
=> Add method to set admin meta to DAO

src/us/kbase/workspace/database/ObjectResolver.java, src/us/kbase/workspace/database/PermissionsCheckerFactory.java, src/us/kbase/workspace/database/Workspace.java, src/us/kbase/workspace/kbase/admin/AdministrationCommandSetInstaller.java, src/us/kbase/workspace/test/database/mongo/MongoInternalsTest.java, src/us/kbase/workspace/test/kbase/admin/AdministrationCommandSetInstallerTest.java, src/us/kbase/workspace/test/workspace/PermissionsCheckerFactoryTest.java, src/us/kbase/workspace/test/workspace/WorkspaceListenerTest.java, src/us/kbase/workspace/test/workspace/WorkspaceTest.java, src/us/kbase/workspace/test/workspace/WorkspaceTester.java, src/us/kbase/workspace/test/workspace/WorkspaceUnitTest.java
Surprised it's not already there. Anyway, will be needed for the admin object metadata method and also allows us to clean up some other methods that were doing hacky things to get around it.
=> Add admin mode to PermissionsChecker

.github/workflows/test.yml, build.gradle, src/us/kbase/workspace/test/controllers/workspace/WorkspaceController.java
Tested this setup in the Groups service, replacing the workspace controller there
=> Add shadow jar and workspace controller that starts said jar

.github/workflows/test.yml, build.gradle, src/us/kbase/workspace/test/controllers/workspace/WorkspaceController.java
This PR is a duplicate of https://github.com/kbase/workspace_deluxe/pull/726 as codecov seems to be unable to pass without a token, and the token isn't available in a fork. As such, it has already been approved.
Tested this setup in the Groups service, replacing the workspace controller there
=>  Add shadow jar and workspace controller that starts said jar
